WIP SnarkyJS parties uber test: Parties transaction through SnarkyJS/MinaSigner/Mina daemon.
MinaProtocol/mina pull request #10580
Opened 2022-03-22 22:49 UTC by bkase

Explain your changes:
* TODO

Explain how you tested your changes:
* TODO

Closes #10438

2022-03-25 11:57 UTC, mitschabaude commented
!ci-build-me

2022-04-15 14:02 UTC, mitschabaude approved these changes

2022-04-21 13:05 UTC, lk86 approved these changes

2022-04-28 15:52 UTC, deepthiskumar reviewed
There are some new changes in develop that aren't in this branch. Could you rebase against the latest develop before merging?

2022-04-28 15:52 UTC, deepthiskumar commented on src/app/test_executive/snarkyjs.ml
> +                (Set_or_keep.Set (Field.of_int 3))
`expected`?

2022-04-28 18:03 UTC, psteckler requested changes
Please fill in the initial comment with the PR purpose and describing the testing that was done.

2022-04-29 18:16 UTC, mitschabaude commented
I think we're good to go :D

2022-04-29 18:19 UTC, deepthiskumar approved these changes

2022-04-29 20:23 UTC, psteckler approved these changes

2022-04-30 05:41 UTC, merged