Steven ci podspec
MinaProtocol/mina pull request #10728
Opened 2022-04-08 18:54 UTC by stevenplatt

Explain your changes:
This PR holds three changes: 
- Update the base image used for integration test nodes to [image-name]:latest format. Because the pod configuration is set to always pull a new copy of the image, the base configuration should always include the latest updates (compared to before where the release was static assigned). 
- Updated resource requests and limits. Configuration files used to spin up nodes within integration tests are now set with a fixed request and matched limit. This is intended to resolve scenarios where a test begins, but a node is lost during testing due to it being allowed to scale after deployment (to a level beyond what the parent container can provide - resulting in it being dropped). A few pods has also received an increase in resources allocation to better match the [spec recommended to community members](https://docs.minaprotocol.com/en/getting-started). 
- Additional `dirtyWhen` line added to `TestnetIntegrationTests.dhall`. This will run the full CI suite of test whenever the Helm directory is updated. This is important since integration tests use these underlying helm files to deploy nodes. 

Explain how you tested your changes:
Because this change is directly applying to the nodes that run integration tests, the `ci-build-me` label is added to confirm that all test are still able to complete and behave as expected. 

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2022-04-08 19:59 UTC, samuelarogbonlo approved these changes

2022-04-09 22:05 UTC, Hasancan2 approved these changes

2022-04-11 14:48 UTC, lk86 requested changes
When you make changes to helm charts, you must also increment the version number in Chart.yaml, replace the `artifacthub.io/changes` line with a description of the changes you made, and run `make changelog` to update CHANGES.md. This will give CI enough information to publish a clear and useful artifact to artifacthub to match your work.

2022-05-20 16:43 UTC, stevenplatt commented
Closing the current pull request and will revisit submitting at a future date with requested changes. Tagging @matheus-o1labs for visibility.

2022-05-20 16:43 UTC, closed without merging