remove token permissions
MinaProtocol/mina pull request #11015
Opened 2022-05-19 16:42 UTC by deepthiskumar

Remove `token_permissions` from accounts

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2022-05-19 17:41 UTC, psteckler approved these changes

2022-05-26 02:02 UTC, mrmr1993 requested changes

2022-05-26 02:02 UTC, mrmr1993 commented on src/lib/mina_graphql/mina_graphql.ml
> +                   Account_id.equal aid token_owner )
This check will never be true, but always returning `false` may be misleading. Replace the whole body of this response with `None`.

2024-01-11 06:33 UTC, mrmr1993 commented
The same effect was achieved by a different PR. Closing.

2024-01-11 06:33 UTC, closed without merging