Add dhall to toolchain
MinaProtocol/mina pull request #11044
Opened 2022-05-23 12:13 UTC by balsoft

Adds dhall to Mina toolchain. Needed for https://github.com/MinaProtocol/mina/pull/10939

2022-05-24 07:12 UTC, yorickvP approved these changes

2022-05-24 07:30 UTC, yorickvP commented
CI Failure is genuine: E: Unable to locate package dhall

2022-05-25 07:28 UTC, yorickvP commented on dockerfiles/stages/3-toolchain
> +    && sudo mv /tmp/dhall/bin/dhall /usr/bin
```suggestion
    && sudo tar --extract --file=/tmp/dhall.tar.bz2 --bzip2 --directory=/usr bin/dhall
```

2022-05-25 07:28 UTC, yorickvP commented on dockerfiles/stages/3-toolchain
> +    && sudo mv /tmp/dhall-bash/bin/dhall-to-bash /usr/bin
```suggestion
    && sudo tar --extract --file=/tmp/dhall-bash.tar.bz2 --bzip2 --directory=/usr bin/dhall-to-bash
```

2022-05-25 07:28 UTC, yorickvP commented on dockerfiles/stages/3-toolchain
> +    && sudo mv /tmp/dhall-yaml/bin/dhall-to-yaml /usr/bin
```suggestion
    && sudo tar --extract --file=/tmp/dhall-yaml.tar.bz2 --bzip2 --directory=/usr bin/dhall-to-yaml
```

2022-05-25 07:31 UTC, yorickvP commented
> Error response from daemon: Dockerfile parse error line 305: unknown instruction: &&

Need backslashes at the end of the lines

2022-05-30 12:41 UTC, yorickvP commented
lgtm

2022-05-31 21:01 UTC, lk86 requested changes

2022-05-31 21:01 UTC, lk86 commented on dockerfiles/stages/3-toolchain
> +RUN curl -sL https://github.com/dhall-lang/dhall-haskell/releases/download/1.41.1/dhall-1.41.1-x86_64-linux.tar.bz2 > /tmp/dhall.tar.bz2 \
Also can you add a new DHALL_VERSION=1.41.1 to the top of this file and potentially the DHALL_JSON_VERSION and DHALL_BASH_VERSION

2022-05-31 21:04 UTC, yorickvP commented on dockerfiles/stages/3-toolchain
> +RUN curl -sL https://github.com/dhall-lang/dhall-haskell/releases/download/1.41.1/dhall-1.41.1-x86_64-linux.tar.bz2 > /tmp/dhall.tar.bz2 \
We could do `curl | tar` to avoid the temporary file

2022-06-01 16:07 UTC, lk86 approved these changes

2022-06-02 10:20 UTC, merged