Rm transaction_expiry_hr
MinaProtocol/mina pull request #12231
Opened 2022-11-17 16:00 UTC by ghost-not-in-the-shell

### Welcome 👋

Thank you for contributing to Mina! Please see `CONTRIBUTING.md` if you haven't
yet. In that doc, there are more details around how to start our CI.

If you cannot complete any of the steps below, please ask for help from a core
contributor.

### Incomplete Work

We feel it's important that everyone is comfortable landing incomplete projects
so we don't keep PRs open for too long (especially on develop). To do this we
don't want to forget that something is incomplete, don't want to be blocked on
landing things, and we don't want to land anything that breaks the daemon. We
don't want to forget to test the incomplete things whenever they are completed,
and finally we want to clean up after ourselves: any temporary cruft gets
completely removed before a project is considered done.

To achieve the above, we wish to keep track of incomplete work using a draft of
the release notes. We can share this part of the current draft at anytime with
external contributors. Moreover, we will review this draft during hardforks.

To ship incomplete work, put it behind feature flags -- prefer a runtime
CLI/daemon-config-style flag if possible, and only if necessary fallthrough to
compile time flags. Note that if you put code behind a compile time flag, you
_must_ ensure that CI is building all possible code paths. Don't land something
that doesn't build in CI.

## PLEASE DELETE EVERYTHING ABOVE THIS LINE
---

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2022-11-17 16:08 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-29 08:03 UTC, deepthiskumar requested changes

2022-11-29 08:03 UTC, deepthiskumar commented on src/lib/network_pool/transaction_pool.ml
> -    let%test_unit "Expired transactions that are already in the pool are \
This test never tested the `valid_until` field of a zkApp transaction. Could you please add a test similar to this but testing that expired zkApp transactions (based on the `valid_until` field) are removed from the pool?

2022-12-02 20:56 UTC, deepthiskumar commented on src/lib/mina_base/user_command.ml
> +      match fee_payer.Account_update.Fee_payer.body.valid_until with
good catch!

2022-12-02 20:56 UTC, deepthiskumar approved these changes

2022-12-05 15:59 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-12-06 15:29 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-12-08 08:12 UTC, merged