Remove timestamp and global_slot_since_hard_fork in precondition
MinaProtocol/mina pull request #12234
Opened 2022-11-17 18:08 UTC by ghost-not-in-the-shell

### Welcome 👋

Thank you for contributing to Mina! Please see `CONTRIBUTING.md` if you haven't
yet. In that doc, there are more details around how to start our CI.

If you cannot complete any of the steps below, please ask for help from a core
contributor.

### Incomplete Work

We feel it's important that everyone is comfortable landing incomplete projects
so we don't keep PRs open for too long (especially on develop). To do this we
don't want to forget that something is incomplete, don't want to be blocked on
landing things, and we don't want to land anything that breaks the daemon. We
don't want to forget to test the incomplete things whenever they are completed,
and finally we want to clean up after ourselves: any temporary cruft gets
completely removed before a project is considered done.

To achieve the above, we wish to keep track of incomplete work using a draft of
the release notes. We can share this part of the current draft at anytime with
external contributors. Moreover, we will review this draft during hardforks.

To ship incomplete work, put it behind feature flags -- prefer a runtime
CLI/daemon-config-style flag if possible, and only if necessary fallthrough to
compile time flags. Note that if you put code behind a compile time flag, you
_must_ ensure that CI is building all possible code paths. Don't land something
that doesn't build in CI.

## PLEASE DELETE EVERYTHING ABOVE THIS LINE
---

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2022-11-18 15:42 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-18 16:21 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-21 20:31 UTC, mitschabaude approved these changes
Nice change!

2022-11-22 16:01 UTC, ghost-not-in-the-shell commented on frontend/mina-signer/tests/party.test.ts
>              totalCurrency: { lower: "0", upper: "18446744073709551615" },
I think I already removed that.

2022-11-28 17:08 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-28 18:13 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-29 08:05 UTC, deepthiskumar requested changes

2022-11-30 17:41 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-30 18:57 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-11-30 19:37 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-12-01 09:57 UTC, mitschabaude commented on frontend/mina-signer/tests/party.test.ts
>              totalCurrency: { lower: "0", upper: "18446744073709551615" },
I meant in this test file!

2022-12-02 14:08 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-12-02 18:29 UTC, ghost-not-in-the-shell commented
!ci-build-me

2022-12-02 20:48 UTC, deepthiskumar approved these changes

2022-12-06 10:51 UTC, merged