Verification refcounted key hash table in transaction pool
MinaProtocol/mina pull request #12398
Opened 2022-12-19 23:19 UTC by bkase

Adds a verification key refcounted table in the transaction pool to track keys as they enter/exit the mempool.

Also adjusted the `User_command.to_verifiable` to be more flexible with its fallback rather than assume it's a ledger lookup.

Plan to test this as part of #12364 

Fixes XXX

2022-12-19 23:23 UTC, psteckler commented on src/lib/network_pool/transaction_pool.ml
> +              if Int.equal x 1 then None else Some (x - 1, value) )
can use `x = 1`

2022-12-20 09:09 UTC, deepthiskumar requested changes
the ref counts need to be updated in this function as well. 
https://github.com/MinaProtocol/mina/blob/827d49a0c4714f01dae199c6782e825d92eca369/src/lib/network_pool/transaction_pool.ml#L471

2022-12-20 09:09 UTC, deepthiskumar commented on src/lib/staged_ledger/staged_ledger.ml
> +              (* TODO: what are we supposed to do here? *)
I don't think we need to do anything here. `Verifiable.create` does what's required

2022-12-20 09:09 UTC, deepthiskumar commented on src/lib/mina_base/zkapp_command.ml
> +  let find_vk_via_ledger ~ledger ~get ~location_of_account _vk_hash account_id =
nit: make it a labelled arg `~expected_vk_hash`?

2022-12-20 20:43 UTC, bkase commented on src/lib/mina_base/zkapp_command.ml
> +                          "TODO: Lookup the vk_hash inside this account update"
oops, thanks forgot about this

2022-12-21 23:19 UTC, bkase commented
I am very not confident that I covered the `handle_transition_frontier_diff` is properly instrumented with vk_refcount_table inc and dec (this is the scary part of using the ref counted table). Please review very carefully.

2023-01-03 18:51 UTC, mrmr1993 commented on src/lib/staged_ledger/staged_ledger.ml
> +                  (Zkapp_command.Verifiable.find_vk_via_ledger ~ledger ~get
Won't this get the wrong vk if one zkApp command sets it and a later one attempts to use it? It feels like we need to accumulate across all of the commands.

2023-01-03 18:51 UTC, mrmr1993 commented on src/lib/mina_base/zkapp_command.ml
> +        Ok vk
+1

2023-01-03 18:51 UTC, mrmr1993 commented on src/lib/mina_base/zkapp_command.ml
> +      ~find_vk:(Verifiable.find_vk_via_ledger ~ledger ~get ~location_of_account)
Does it make sense to pass this in as an argument? Looking in the ledger is not always the right thing to do (although it's possible this is only used in tests..)

2023-01-03 18:51 UTC, mrmr1993 commented on src/lib/network_pool/transaction_pool.ml
> +                                    F.Map.find running_cache vk_hash
Does it make sense to factor out (some of) this logic into a function in `Zkapp_command`? It seems like we probably want something similar to this in (at least) the staged ledger diff application logic too.

2023-01-03 18:51 UTC, mrmr1993 commented on src/lib/network_pool/transaction_pool.ml
> +    let extract_vks : User_command.t -> Verification_key_wire.t List.t =
This probably shouldn't live here. In `User_command` / `Zkapp_command` / both?

2023-01-06 04:42 UTC, bkase commented
!ci-build-me

2023-01-13 18:30 UTC, bkase commented
!ci-build-me

2023-01-17 21:25 UTC, mrmr1993 approved these changes
LGTM, but I suspect the zkapps_examples are broken due to the `patch` (and if they're not, we're not testing them properly / something is broken!)

2023-01-17 21:25 UTC, mrmr1993 commented on src/lib/network_pool/transaction_pool.ml
> +      let sequence_or_error (xs : 'a Or_error.t list) : 'a list Or_error.t =
Nit: `Or_error.combine_errors`?

2023-01-17 21:25 UTC, mrmr1993 commented on src/lib/zkapps_examples/zkapps_examples.ml
> +            (* the vk hash is a dummy, to be patched with `patch_verification_key_hashes`, below *)
Nit: shift this comment down?

2023-01-17 21:25 UTC, mrmr1993 commented on src/lib/transaction_snark/test/zkapps_examples/actions/actions.ml
> +        Zkapps_examples.patch_verification_key_hashes ~ledger zkapp_command0
I'm not sure that it's valid to patch at this stage.. I think you need to pass the verification key hash into the circuit while it's constructing the transaction, in the same way we do for `public_key`, `token_id`, `caller`, etc.

2023-01-21 09:48 UTC, merged