Add `Blind_call` call type
MinaProtocol/mina pull request #12512
Opened 2023-01-13 14:40 UTC by mrmr1993

This PR adds the `Blind_call` call type. To compare the call semantics of this with the others:
* `Call` repesents a plain call, conveying permission to the child (and potentially it's children, via delegate call) to use the `token_id` derived from the caller's account ID
* `Delegate_call` represents a call as if this node was not in the stack, passing permission to use the `token_id` given to this node down to its child
* `Blind_call` is a call that conveys no permission to its children to use its `token_id`
  - the current proposed semantics are that this also resets the stack of callers visible to the zkApp. Do we also need a `No_token_call` that also doesn't pass `token_id`, but *doesn't* reset the stack?

This builds upon #12450.

Checklist:

- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

2023-01-13 14:40 UTC, mrmr1993 commented
!ci-build-me

2023-01-13 19:39 UTC, psteckler commented
Can the above description be added to where the data type is defined in the code, for easy future reference?

2023-01-14 00:27 UTC, psteckler requested changes
Please add the description of the intended semantics where the call type is defined.

2023-01-18 15:16 UTC, mrmr1993 commented
!ci-build-me

2023-01-18 17:06 UTC, mrmr1993 commented
!ci-build-me

2023-01-18 18:23 UTC, psteckler approved these changes
one nit, otherwise good

2023-01-18 19:34 UTC, mrmr1993 commented
!ci-build-me

2023-01-18 20:39 UTC, mitschabaude commented on src/lib/mina_base/account_update.ml
> +              Field.Checked.Assert.equal sum sum_squared )
I guess this `check` runs in addition to the check that the two fields are booleans individually?

2023-01-18 20:40 UTC, mitschabaude commented on src/lib/mina_base/account_update.ml
> +              Field.Checked.Assert.equal sum sum_squared )
ah I guess that's the `typ.check x` above

2023-01-18 20:40 UTC, mitschabaude commented on src/lib/mina_base/account_update.ml
> +              Field.Checked.Assert.equal sum sum_squared )
👍🏻

2023-01-23 14:07 UTC, mrmr1993 commented
!ci-build-me

2023-01-23 21:52 UTC, mrmr1993 commented
!ci-build-me

2023-01-24 06:53 UTC, deepthiskumar commented on src/lib/mina_ledger/ledger.ml
> +                (mk_account_update_body None_given No token_account1
This should be `Parents_own_token`, right? `custom_token_id` is owned by `token_owner`

2023-01-24 06:53 UTC, deepthiskumar commented on src/lib/mina_ledger/ledger.ml
> +                (mk_account_update_body Signature No token_account1
Here as well and below where ever `custom_token_id` is used

2023-01-24 06:53 UTC, deepthiskumar commented on src/app/test_executive/zkapps.ml
> +                    (mk_account_update_body Signature No token_accounts.(0)
This should be `Parents_own_token` as well

2023-01-24 06:53 UTC, deepthiskumar commented on src/app/test_executive/zkapps.ml
> +                    (mk_account_update_body Signature No token_owner
`Parents_own_token`

2023-01-24 06:53 UTC, deepthiskumar commented on src/app/test_executive/zkapps.ml
> +                        (mk_account_update_body Signature No token_accounts.(2)
`Parents_own_token`

2023-01-24 06:53 UTC, deepthiskumar commented on src/app/test_executive/zkapps.ml
> +                    (mk_account_update_body Signature No token_accounts.(0)
`Parents_own_token` everywhere in this txn where `custom_token_id` is used

2023-01-24 06:53 UTC, deepthiskumar commented on src/app/test_executive/zkapps.ml
> +                    (mk_account_update_body Signature No token_accounts.(1)
`Parents_own_token` everywhere in this txn where `custom_token_id` or `custom_token_id2` is used

2023-01-25 10:08 UTC, joaosreis approved these changes

2023-01-25 19:35 UTC, merged