use string instead of boolean
MinaProtocol/mina pull request #13232
Opened 2023-05-15 15:52 UTC by ghost-not-in-the-shell

Explain your changes:
This PR uses string for compilation option for the network.

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2023-05-15 15:53 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-05-26 17:52 UTC, mrmr1993 requested changes

2023-05-26 17:52 UTC, mrmr1993 commented on src/lib/signature_lib/schnorr.ml
> +  let network_id_other = Char.of_int_exn 2
We want to achieve domain separation between each of these new domains too, but I don't think the mechanism is decided yet. Hard-coding 2 here is cryptographically dangerous.
Can you delete this, and put a `failwith "TODO"` where it's used below, to make sure this doesn't leak out into production?

2023-05-26 17:52 UTC, mrmr1993 commented on src/lib/signature_lib/schnorr.ml
> +        network_id_other
`failwith` here

2023-05-26 17:52 UTC, mrmr1993 commented on src/lib/signature_lib/schnorr.ml
> +              network_id_other )
And here

2023-05-26 17:52 UTC, mrmr1993 commented on src/lib/signature_lib/schnorr.ml
> +              network_id_other )
Here also

2023-05-29 16:16 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-05-29 16:45 UTC, bkase commented on src/lib/hash_prefixes/hash_prefixes.ml
> +let signature_other chain_name = create (chain_name ^ "Siganture")
nit: `Signature` not `Siganture`

2023-05-30 19:32 UTC, mrmr1993 approved these changes

2023-05-31 21:19 UTC, deepthiskumar commented on src/lib/string_sign/string_sign.ml
> +              keypair.public_key s )
For this and all the below tests, could you also add a check that they can be verified with the intended signature kind?

2023-06-05 16:44 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-06-06 15:19 UTC, merged