Feature/include network id for account update hash berk
MinaProtocol/mina pull request #13880
Opened 2023-08-16 20:52 UTC by ghost-not-in-the-shell

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2023-08-16 20:53 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-17 19:03 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-17 19:40 UTC, ghost-not-in-the-shell commented on src/lib/hash_prefixes/hash_prefixes.ml
> +let zkapp_body ?(chain = Mina_signature_kind.t) =
Sure.

2023-08-24 00:37 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-24 01:31 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-24 01:35 UTC, mrmr1993 approved these changes

2023-08-24 07:17 UTC, Trivo25 approved these changes

2023-08-24 22:28 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-25 00:36 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-25 12:54 UTC, deepthiskumar requested changes

2023-08-25 12:54 UTC, deepthiskumar commented on src/app/test_executive/zkapps.ml
> +                      , zkapp_command_single_account_update ) =
nit: could you rename this to something more meaningful- `zkapp_command_cross_network_replay` or something?

2023-08-25 12:54 UTC, deepthiskumar commented on src/lib/staged_ledger/staged_ledger.ml
> +       Combining together with the test that uses pickles directly, these 2 tests would make sure that
can you edit the comment to describe this test? What are the 2 tests here?

2023-08-25 12:54 UTC, deepthiskumar commented on src/lib/transaction_snark/transaction_snark.ml
> +    module Single_account_update_spec = struct
Can you add a comment to describe what this is for (as there are a few different specs) and when it can be used?

2023-08-25 14:54 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-25 16:28 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-28 14:02 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-08-28 14:49 UTC, deepthiskumar approved these changes

2023-08-28 14:50 UTC, deepthiskumar commented
!approved-for-mainnet

2023-08-28 17:11 UTC, merged