Add tool to generate ledger accounts for testing
MinaProtocol/mina pull request #14087
Opened 2023-09-11 14:04 UTC by georgeee

To test cluster on large ledgers it's useful to have a tool to randomly generate ledger accounts for testing.

Usage: `mina advanced generate-ledger-accounts -n 200000 > ledger.json` to generate 200'000 accounts.

Bonus: to wire the accounts generated to file `ledger.json` into a `daemon.stub.json` stub, use the following command (also sets genesis timestamp to a new value):

```bash
jq --arg timestamp $( d=$(date +%s); date -u -d @$((d - d % 180 + 180)) +%FT%H:%M:%S+00:00 ) --slurpfile accounts ledger.json '.ledger.accounts |= . + $accounts[0] | .genesis.genesis_state_timestamp |= $timestamp'  < daemon.stub.json > daemon.json
```

Explain your changes:
* Implement a new command

Explain how you tested your changes:
* Generated a ledger, ledger testes against a Mina node

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

2023-09-11 15:44 UTC, psteckler approved these changes

2023-09-13 14:41 UTC, georgeee commented
!ci-build-me

2023-10-16 22:27 UTC, deepthiskumar commented on src/app/cli/src/init/client.ml
> +    ; ("generate-ledger-accounts", Cli_lib.Commands.generate_ledger_accounts)
Can we add a separate group for commands used only for testing?

2023-10-16 22:27 UTC, deepthiskumar requested changes
Separate command group for testing

2024-09-13 13:34 UTC, georgeee commented
!ci-build-me

2024-09-13 13:42 UTC, georgeee commented
!ci-build-me

2024-09-13 14:42 UTC, georgeee commented
!ci-nix-build

2024-09-14 08:35 UTC, dkijania approved these changes

2024-09-14 08:37 UTC, dkijania commented
I have only a general observation that we are mixing test related and debug related command with production ones... I would warmly welcome some cleanup PR which will segregate command so it is crystal clear that commands from let's say mina internal test are purely for test purposes and should not be used on production

2024-09-14 10:19 UTC, merged

2024-09-14 10:37 UTC, georgeee commented
@dkijania opened PR #16048 based on feedback above