Remove unused type parameters berkeley
MinaProtocol/mina pull request #14106
Opened 2023-09-13 12:40 UTC by rbonichon

This is a slimmed down version of #14080 for `berkeley`

2023-09-13 12:41 UTC, rbonichon commented
!ci-build-me

2023-09-13 12:53 UTC, mrmr1993 commented
!approved-for-mainnet

2023-09-13 12:53 UTC, mrmr1993 approved these changes

2023-10-16 22:11 UTC, deepthiskumar requested changes
@rbonichon `berkeley` branch is currently in code freeze and we are taking only essential changes for berkeley HF and non-risky CI or documentation changes. Please make such changes against `develop` branch. Thanks!

2023-11-29 21:04 UTC, closed without merging