Feature/verification key update txn version
MinaProtocol/mina pull request #14407
Opened 2023-10-21 00:49 UTC by ghost-not-in-the-shell

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2023-10-21 00:52 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-10-21 16:45 UTC, psteckler commented on src/app/archive/lib/processor.ml
> +    | Error _ ->
should the error also be printed?

2023-10-23 13:14 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-10-23 15:39 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-10-23 19:17 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-10-30 14:34 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-10-31 14:02 UTC, Trivo25 commented
!ci-build-me

2023-11-27 15:23 UTC, Trivo25 approved these changes

2023-11-29 12:37 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-11-29 12:50 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-11-29 13:03 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-11-29 13:04 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-11-29 15:05 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-11-29 17:32 UTC, deepthiskumar commented
!ci-nightly-me

2023-12-04 15:39 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-04 17:04 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-04 18:24 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-05 12:47 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-05 13:34 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-05 13:35 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-05 16:27 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-05 21:00 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-07 18:12 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-07 19:18 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-14 15:50 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-14 16:40 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-14 20:06 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-14 20:24 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-15 14:02 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-15 20:05 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-18 15:39 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-18 17:47 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-18 19:39 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-18 20:34 UTC, nholland94 requested changes
Overall LGTM, but I would really like to see more clarity in how all of this is surface to the transaction logic. That could mean just a better name for this `fallback` function, or moving this fallback logic explicitly inside of the transaction logic. But just this generic `fallback` function makes it a bit hard to understand what's going on within the transaction logic code, which is something I think we should optimize for in our changes there.

2023-12-18 20:34 UTC, nholland94 commented on src/lib/mina_base/zkapp_command.ml
> +      | Set { set_verification_key = auth, txn_version; _ } ->
Do you not get a warning for this unused `auth` value? If so, we should work to re-enable the unused value warnings for this file (in a separate PR).

2023-12-19 14:30 UTC, ghost-not-in-the-shell commented
!ci-build-me

2023-12-19 14:30 UTC, ghost-not-in-the-shell commented
!ci-nightly-me

2023-12-19 17:40 UTC, nholland94 approved these changes

2023-12-21 12:11 UTC, mrmr1993 requested changes
LGTM, but please update the proof caches for the transaction snark tests now that the circuits have changed. You can find some details on how to do that [here](https://github.com/MinaProtocol/mina/tree/feature/verification-key-update-txn-version/src/lib/transaction_snark/test#readme).

2024-01-02 16:40 UTC, ghost-not-in-the-shell commented on src/app/test_executive/block_production_priority.ml
> +        (let open Test_account in
I modified the `Test_account` to do testing of verification key update in integration tests. Unfortunately this change propagates to other integration tests.

 I do realize that the changes to protocol and the changes to the tests seem like rather unrelated in this PR. Maybe I should also have a chain of PRs that separate the change itself and the change to the integration tests to make review easier.

2024-01-02 17:39 UTC, ghost-not-in-the-shell commented
!ci-build-me

2024-01-08 16:10 UTC, ghost-not-in-the-shell commented
!ci-build-me

2024-01-08 16:34 UTC, mrmr1993 approved these changes

2024-01-11 18:44 UTC, ghost-not-in-the-shell commented
!ci-build-me

2024-01-16 19:01 UTC, ghost-not-in-the-shell commented
!ci-build-me

2024-01-16 19:22 UTC, ghost-not-in-the-shell commented
!ci-build-me

2024-01-19 00:47 UTC, deepthiskumar commented
!ci-nightly-me

2024-01-19 00:49 UTC, deepthiskumar commented
!ci-build-me

2024-01-19 00:49 UTC, deepthiskumar commented
!ci-nightly-me

2024-01-19 00:51 UTC, deepthiskumar commented
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1145

2024-01-19 05:35 UTC, deepthiskumar commented
Waiting for all the intg tests to pass

2024-01-19 07:18 UTC, deepthiskumar commented
!approved-for-mainnet

2024-01-19 12:20 UTC, merged