When comparing `Field.t` values, avoid the conversion to bigint
MinaProtocol/mina pull request #14597
Opened 2023-11-22 02:05 UTC by tizoc

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2023-11-22 11:17 UTC, tizoc commented
!ci-build-me

2023-11-22 11:40 UTC, tizoc commented
!ci-build-me

2023-11-22 12:18 UTC, georgeee approved these changes
I support this change: it strictly streamlines the code.

I ran a round of this fix with the `ledger test-apply` tool and saw performance improvement of around 10%. It might be a statistical aberration though, but looks like even if there is a performance improvement, it;'s a marginal one.

2023-11-22 13:19 UTC, mrmr1993 requested changes
Per [the original discussion](https://github.com/MinaProtocol/mina/pull/14595#pullrequestreview-1742896016) please create a rust binding that explicitly calls `into_repr` and use that instead.

From the comment on the rust function backing compare:
```
        /// users should use this `Ord` for applications where
        /// any ordering suffices (like in a BTreeMap), and not in applications
        /// where a particular ordering is required.
```

2023-11-22 15:31 UTC, mrmr1993 commented
@tizoc either is fine, whichever you prefer

2023-11-22 18:29 UTC, mrmr1993 approved these changes

2023-11-27 20:40 UTC, tizoc commented
This one is included in #14599, leaving it for now because this one is already approved and the other isn't, but they are related.

2023-12-04 22:53 UTC, tizoc commented
This is included in #14599 which got merged already, closing.

2023-12-04 22:53 UTC, closed without merging