Dkijania/revive extract dump archive test
MinaProtocol/mina pull request #14712
Opened 2023-12-13 18:50 UTC by dkijania

### Welcome 👋

Thank you for contributing to Mina! Please see `CONTRIBUTING.md` if you haven't
yet. In that doc, there are more details around how to start our CI.

If you cannot complete any of the steps below, please ask for help from a core
contributor.

### Incomplete Work

We feel it's important that everyone is comfortable landing incomplete projects
so we don't keep PRs open for too long (especially on develop). To do this we
don't want to forget that something is incomplete, don't want to be blocked on
landing things, and we don't want to land anything that breaks the daemon. We
don't want to forget to test the incomplete things whenever they are completed,
and finally we want to clean up after ourselves: any temporary cruft gets
completely removed before a project is considered done.

To achieve the above, we wish to keep track of incomplete work using a draft of
the release notes. We can share this part of the current draft at anytime with
external contributors. Moreover, we will review this draft during hardforks.

To ship incomplete work, put it behind feature flags -- prefer a runtime
CLI/daemon-config-style flag if possible, and only if necessary fallthrough to
compile time flags. Note that if you put code behind a compile time flag, you
_must_ ensure that CI is building all possible code paths. Don't land something
that doesn't build in CI.

## PLEASE DELETE EVERYTHING ABOVE THIS LINE
---

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2023-12-13 21:06 UTC, dkijania commented
!ci-build-me

2023-12-29 08:57 UTC, dkijania commented
!ci-build-me

2024-05-13 20:18 UTC, dkijania commented
!ci-build-me

2024-07-28 08:56 UTC, dkijania commented
!ci-build-me

2024-08-01 14:52 UTC, dkijania commented
!ci-build-me

2024-08-02 09:10 UTC, dkijania commented
!ci-build-me

2024-08-12 17:02 UTC, dkijania commented
!ci-build-me

2024-08-12 20:02 UTC, dkijania commented
!ci-build-me

2024-08-13 08:49 UTC, dkijania commented
!ci-build-me

2024-08-13 11:28 UTC, dkijania commented
!ci-build-me

2024-08-15 12:21 UTC, dkijania commented
!ci-build-me

2024-08-15 15:21 UTC, dkijania commented
!ci-build-me

2024-08-19 07:10 UTC, SanabriaRusso approved these changes

2024-08-19 17:13 UTC, dkijania commented
!ci-build-me

2024-08-20 19:01 UTC, dkijania commented
!ci-build-me

2024-08-20 20:16 UTC, dkijania commented
!ci-build-me

2024-08-21 15:35 UTC, dkijania commented
!ci-build-me

2024-08-21 16:48 UTC, georgeee requested changes

2024-08-21 16:48 UTC, georgeee commented on scripts/archive/missing-blocks-guardian.sh
> +    echo "    BLOCKS_FORMAT           Block fromat type. Possible values: [precomputed/extensional] (default: precomputed)"
```suggestion
    echo "    BLOCKS_FORMAT           Block format type. Possible values: [precomputed/extensional] (default: precomputed)"
```

2024-08-21 16:48 UTC, georgeee commented on src/app/extract_blocks/extract_blocks.ml
> +              |> Option.map ~f:(fun network -> network ^ "-")
```suggestion
              |> Option.value_map ~default:"" ~f:(fun network -> network ^ "-")
```

2024-08-21 16:48 UTC, georgeee commented on src/app/extract_blocks/extract_blocks.ml
> +              |> Option.map ~f:(fun network -> network ^ "-")
And remove the next line

2024-08-21 16:48 UTC, georgeee commented on src/lib/integration_test_lib/util.ml
> +    | None ->
Suggest the following rewrite for the entire `let list = ...`:

```suggestion
match env with
    | Some (`Extend list) ->List.map list ~f:(fun (key, value) -> `String (key ^ "=" ^ value))
    | _ -> []
```

2024-08-21 16:48 UTC, georgeee commented on src/lib/precomputed_block/precomputed_block.ml
> +(* Precomputed_block.t type has changed from mainnet, too hard to recreate old type
Do you mean current `compatible` diverged from actual `mainnet`? Or the comment isn't up-to-date?

2024-08-21 16:48 UTC, georgeee commented on src/lib/precomputed_block/precomputed_block.ml
> +(* Couldn't get the deriver to generate a valid of_yojson implementation here for some reason, so we hand=write one instead *)
I wonder, what was the reason?

2024-08-21 16:48 UTC, georgeee commented on src/lib/precomputed_block/precomputed_block.ml
> +(* Precomputed_block.t type has changed from mainnet, too hard to recreate old type
It's not clear to me why this new file is in this PR

2024-08-21 16:48 UTC, georgeee commented on src/test/mina_automation/docker.ml
> +open Integration_test_lib
Can new files from `mina_automation` be extracted to a seperate PR, and perhaps a README to be added?

It's hard to understand what's happening here, and I'd prefer to review it separately.

2024-08-24 12:27 UTC, dkijania commented
!ci-build-me

2024-08-26 08:29 UTC, dkijania commented
!ci-build-me

2024-08-26 22:21 UTC, dkijania commented
!ci-build-me

2024-08-28 09:29 UTC, dkijania commented
!ci-build-me

2024-08-28 15:47 UTC, dkijania commented
!ci-build-me

2024-08-28 21:19 UTC, dkijania commented
!ci-build-me

2024-08-29 08:39 UTC, dkijania commented
!ci-build-me

2024-09-02 17:08 UTC, dkijania commented
!ci-build-me

2024-09-05 17:06 UTC, dkijania commented
!ci-build-me

2024-09-09 19:23 UTC, dkijania commented
!ci-build-me

2024-09-09 21:02 UTC, dkijania commented
!ci-build-me

2024-09-16 09:40 UTC, dkijania commented
!ci-build-me

2024-09-16 18:43 UTC, dkijania commented
!ci-build-me

2024-09-17 18:51 UTC, georgeee approved these changes
Left a couple of minor comments

2024-09-17 18:51 UTC, georgeee commented on src/test/archive/patch_archive_test/patch_archive_test.ml
> +    |> List.map ~f:(fun _ -> Random.int (List.length extensional_files))
```suggestion
    List.init missing_blocks_count ~f:(fun _ -> Random.int (List.length extensional_files))
```

2024-09-17 18:51 UTC, georgeee commented on src/test/archive/patch_archive_test/sql.ml
> +      state_hash
Looks like this model isn't used in the PR

2024-09-17 20:26 UTC, dkijania commented
!ci-build-me

2024-09-18 14:39 UTC, dkijania commented
!ci-build-me

2024-09-19 08:52 UTC, dkijania commented
!ci-build-me

2024-09-19 14:26 UTC, dkijania commented
!ci-build-me

2024-09-23 06:29 UTC, dkijania commented
!ci-build-me

2024-09-23 16:20 UTC, dkijania commented
!ci-build-me

2024-09-23 21:29 UTC, dkijania commented
!ci-build-me

2024-09-24 12:29 UTC, dkijania commented
!ci-build-me

2024-09-29 18:11 UTC, dkijania commented
!ci-build-me

2024-09-30 08:49 UTC, dkijania commented
!ci-build-me

2024-09-30 15:50 UTC, dkijania commented
!ci-build-me

2024-10-01 21:26 UTC, dkijania commented
!ci-build-me

2024-10-02 08:42 UTC, dkijania commented
!ci-build-me

2024-10-07 18:55 UTC, dkijania commented
!ci-build-me

2024-10-10 19:11 UTC, dkijania commented
!ci-build-me

2024-10-14 08:40 UTC, dkijania commented
!ci-build-me

2024-10-14 20:13 UTC, dkijania commented
!ci-build-me

2024-10-16 20:06 UTC, dkijania commented
!ci-build-me

2024-10-17 12:19 UTC, merged