Check if block exists on S3Save - delegation backend performance improvement.
MinaProtocol/mina pull request #14918
Opened 2024-01-18 14:31 UTC by piotr-iohk

Explain your changes:

Prior the change there was a check in `S3Save` if particular item (submission or block) already exists on S3, however whether it existed or not, the item was overwritten anyway. The change only checks whether block exists, and if it does, it skips writing it to S3. I believe that the same check for the submission is not needed as it has a timestamp in the 'filename' so it will be always different.

Explain how you tested your changes:

This change seem to significantly improve response times and memory usage of the application.
Load test has been performed prior and after applying the fix. Results gathered in the report: https://github.com/MinaFoundation/mina-delegation-program-tech/wiki/Load-Test-Report-2024%E2%80%9001%E2%80%9018

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2024-01-18 18:58 UTC, georgeee approved these changes

2024-01-18 18:59 UTC, georgeee requested changes
log messages seem not to be adequate

2024-01-19 07:41 UTC, piotr-iohk commented on src/app/delegation_backend/src/delegation_backend/submit.go
> +				ctx.Log.Warnf("S3Save: object already exists, skipping: %s", path)
Fair enough.

2024-01-19 08:20 UTC, piotr-iohk commented on src/app/delegation_backend/src/delegation_backend/submit.go
> +			ctx.Log.Warnf("S3Save: Error encountered but proceeding with save: %s, error: %v", path, err)
Ah, indeed! Good catch! :+1:

2024-01-19 09:14 UTC, georgeee approved these changes

2024-01-19 11:09 UTC, dkijania commented
!ci-build-me

2024-01-24 10:23 UTC, joaosreis approved these changes

2024-01-24 10:32 UTC, georgeee commented
!ci-build-me

2024-01-24 12:19 UTC, merged