Replayer: convert global slots to avoid to hashes in order to support devnet
MinaProtocol/mina pull request #15302
Opened 2024-03-08 21:12 UTC by dkijania

Changed global_slots_to_avoid to state_hashed_to_avoid array in order to support other networks, like denvet. Before the change, it was not possible to add slots from other network as global slot to avoid on mainnet not necessarily should be skipped in devnet and vice versa

2024-03-08 21:12 UTC, dkijania commented
!ci-build-me

2024-03-08 22:08 UTC, emberian approved these changes

2024-03-12 14:43 UTC, dkijania commented
!ci-build-me

2024-03-12 17:23 UTC, mrmr1993 requested changes

2024-03-12 17:23 UTC, mrmr1993 commented on src/app/replayer/replayer.ml
> +            @ (*mainnet*)
Don't append, just add a comment in the list. Appending is very inefficient.

2024-03-12 17:38 UTC, dkijania commented
!ci-build-me

2024-03-12 20:27 UTC, mrmr1993 approved these changes

2024-03-13 12:28 UTC, dkijania commented
!ci-build-me

2024-03-13 18:19 UTC, merged