Added support for mina-verify-packaged-fork-config
MinaProtocol/mina pull request #15441
Opened 2024-04-02 22:14 UTC by dkijania

Publish mina-verify-packaged-fork-config in CI

2024-04-02 22:14 UTC, dkijania commented
!ci-build-me

2024-04-03 01:34 UTC, emberian requested changes

2024-04-03 01:34 UTC, emberian commented on scripts/deb-builder-helpers.sh
> +  create_control_file "$LEDGER_VALIDATION_DEB" "${DEAMON_DEPS} ,${ARCHIVE_MIGRATION_DEPS} ,${SUGGESTED_DEPS}" 'Berkeley Fork Config Verification Tool' "mina-logproc, ${MINA_DEB_NAME}"
```suggestion
  create_control_file "$LEDGER_VALIDATION_DEB" "${DAEMON_DEPS} ,${ARCHIVE_MIGRATION_DEPS} ,${SUGGESTED_DEPS}" 'Berkeley Fork Config Verification Tool' "mina-logproc, ${MINA_DEB_NAME}"
```

2024-04-03 07:38 UTC, dkijania commented
This is ok for docker and I will update it. However, it is not feasible for debian package. Which should include only script.

2024-04-04 00:48 UTC, emberian approved these changes

2024-04-08 17:26 UTC, closed without merging

2024-04-08 17:26 UTC, dkijania commented
After internal discussion this is not needed as app is already in daemon debian