Use stable nixpkgs version (23.11)
MinaProtocol/mina pull request #15519
Opened 2024-04-16 09:46 UTC by georgeee

Problem: some old unstable nixpkgs is used in flake.nix, which is potentially insecure.

Solution: bump the version of nixpkgs, and a few more flakes.

Explain how you tested your changes:
* [ ] Test build on MacOS
* [x] Test build on Linux

Checklist:

- [x] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [x] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [x] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [x] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [x] All tests pass (CI will check this if you didn't)
- [x] Serialized types are in stable-versioned modules
- [x] Does this close issues? None

2024-04-16 09:46 UTC, georgeee commented
!ci-build-me

2024-04-16 09:57 UTC, georgeee commented
!ci-build-me

2024-04-16 10:11 UTC, georgeee commented
!ci-build-me

2024-04-16 10:45 UTC, georgeee commented
!ci-build-me

2024-04-16 11:21 UTC, georgeee commented
!ci-build-me

2024-04-16 11:59 UTC, L-as commented
Why not use unstable?

2024-04-16 12:51 UTC, georgeee commented
!ci-build-me

2024-04-17 07:18 UTC, georgeee commented
!ci-build-me

2024-04-17 10:54 UTC, georgeee commented
!ci-build-me

2024-04-17 14:01 UTC, rbonichon commented
Can confirm it works on NixOS as is. Have some issues on MacOS. Waiting for others with Apple Silicon to chime in to see if it's local or more global.

2024-04-17 15:02 UTC, joaosreis requested changes
Still has issues building in M1 macOS.

2024-04-17 15:02 UTC, joaosreis commented on flake.nix
> +          if builtins.elem system [ "aarch64-darwin" "x86_64-darwin" ] then
This change is an optional suggestion
```suggestion
          if prev.stdenv.isDarwin then
```

2024-04-17 15:13 UTC, georgeee commented on flake.nix
> +            { rockdb-mina = pkgs.rocksdb; }
Oh, that's a pity. Don't know why I didn't catch it when testing before the commit.

2024-04-17 22:40 UTC, georgeee commented
!ci-build-me

2024-04-17 22:41 UTC, georgeee commented
!ci-toolchain-me

2024-04-17 23:46 UTC, georgeee commented
!ci-build-me

2024-04-18 08:54 UTC, georgeee commented
!ci-build-me

2024-04-18 09:36 UTC, joaosreis approved these changes
It's working well for me! (ARM macOS)

2024-04-18 11:55 UTC, dkijania approved these changes

2024-04-18 12:35 UTC, rbonichon commented
Working well for me too!

2024-04-18 12:36 UTC, rbonichon approved these changes
Works fine. Thanks for the effort @georgeee !

2024-04-18 19:35 UTC, nholland94 commented
!approved-for-mainnet

2024-04-18 19:35 UTC, merged