Merge o1js-main one last time
MinaProtocol/mina pull request #15594
Opened 2024-05-01 12:07 UTC by mitschabaude

- refactor(kimchi_bindings): replace params() with static_params()
- fixup earlier merge
- Revert "Remove ppx_dhall_type [develop]"
- Revert "Revert "Remove ppx_dhall_type [develop]""
- fixup
- dump blockchain snark verification key
- Nix fix attempt.
- attempt to fix nix ci script
- Update snarky to expose callback-oriented helpers, use in pickles step
- WIP Pickles nearly compiling
- Pickles compiles!
- Fixup default `Pickles.compile` to use non-async inductive rules
- Add `Pickles.compile_async`
- Fixup compilation errors (nearly)
- feat(transaction_hash.mli): add hash_zkapp_command function to support hashing of Zkapp_command objects
- make test_fix_domains compile
- adapt tx snark intf
- adapt some tests
- adapt some methods which already return a Deferred
- fixup zkapp examples build
- missing dune file change
- progress: fix_domains runs circuits in order
- work towards running circuits for key generation in sequence
- run stuff in sequence, but for some reason it doesn't work yet
- fix locking
- simplify: reuse promise for entire domain vector
- add debugging
- reuse cs generated for key header
- simplify, add debugging
- reuse sys for wrap keygen
- fix blockchain snark - move known_wrap_keys out of circuit
- simplify: encode wrap keys in main promise
- clean up known wrap key
- undo unnecessary refactors
- remove debug logs
- minimal change to make it work
- fix promise map call semantics
- promise: fix compiler warnings
- promise: add clarifying comment for where we don't support ocaml calls
- cleanup by reusing deferred_of_promise
- make create_trivial_snapp return deferred vk
- adapt tx snark tests
- start fixing snark profiler lib
- fixup heap usage app
- fixup test_executive
- fix test failures by sequentializing logic
- I don't understand why this fixes the transaction snark profiler
- remove log_step and log_wrap
- Assert the relationship between feature flags and verification key
- address feedback pt 1
- get rid of early digest exception
- address feedback pt 2
- bump snarky
- Installing Git LFS at runtime on nixOS container
- revert later: workaround for binary files diff
- fix boolean constraint in case the input is scaled
- don't spam the console when a constraint fails
- update blockchain snark
- replace per-compile lock on circuit runs with a global lock for the entire snarky instance
- CI: make unit-tests job fails if dune runtest fails
- remove chain_to which is now redundant
- Revert "CI: make unit-tests job fails if dune runtest fails"
- Put unit tests back as they should be
- debugging and start making compute prev parts request async
- adapt to name changes
- move vk lookup back into circuit
- remove console logs, adapt logger logs to async
- bump snarky
- revert change which breaks proving inside other circuits
- bump snarky for state consistency reporting
- Revert "remove chain_to which is now redundant"
- Revert "replace per-compile lock on circuit runs with a global lock for the entire snarky instance"
- fix staged ledger tests
- fix pickles optional custom gates test
- Fixup lookup gate with range-check table
- submodules to latest
- Update toolchain images
- Update blockchain vk
- update snarky_test digest and fix logic of printing mismatches
- submodules need to be referred to without a trailing /. to git it's a file, not a folder
- start fixing build
- fix pickles build
- update toolchain images
- fix chunked circuits test
- update codeowners to remove aneesha

2024-05-01 15:15 UTC, mitschabaude commented on src/lib/pickles/wrap_main.ml
it's unfortunate how hard it is here to see actual changes. however, it does seem to me like all the additional `assert_consistent` checks ("Check consistency between index and feature flags") are not in `develop`, and I wonder why, given that this comes from berkeley?

2024-05-01 15:25 UTC, mitschabaude commented
!ci-toolchain-me

2024-05-01 15:56 UTC, MartinMinkov approved these changes

2024-05-01 16:06 UTC, dkijania approved these changes

2024-05-01 18:53 UTC, dannywillems commented on src/lib/pickles/wrap_main.ml
> +            assert_consistent xor_comm xor ;
Seems related to https://github.com/MinaProtocol/mina/pull/15234

2024-05-01 19:00 UTC, dannywillems approved these changes
Reviewed crypto subdirectory + pickles.

2024-05-02 15:40 UTC, mrmr1993 commented
!ci-nightly-me

2024-05-02 15:58 UTC, mrmr1993 requested changes

2024-05-02 15:58 UTC, mrmr1993 commented on buildkite/src/Command/TestExecutive.dhall
> +        ]
Can you revert to the berkeley version? We don't want to do blind retries any more.

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/hard_fork.ml
> +      Async.Thread_safe.block_on_async_exn (fun () ->
This should bind inside the monad instead of using a block.

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/heap_usage/values.ml
> +    Async.Thread_safe.block_on_async_exn (fun () ->
This should probably be a `_ Async.Deferred.t Lazy.t` type that we force and bind over.

2024-05-02 15:58 UTC, mrmr1993 commented on flake.nix
> +          mainnet-caqti-patched = pkgs.ocamlPackages_mina_caqti_patched.mainnet;
These were deliberately deleted on develop. Please do the same here.

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/heap_usage/values.ml
> +  let vk = Async.Thread_safe.block_on_async_exn (fun () -> vk) in
As above, so below

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/peers_reliability_test.ml
> +           @@ Async.Thread_safe.block_on_async_exn (fun () ->
Monad bind

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/verification_key_update.ml
> +      Async.Thread_safe.block_on_async_exn (fun () ->
Expose the `Deferred.t`, bind below.

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/zkapps.ml
> +      @@ Async.Thread_safe.block_on_async_exn (fun () ->
Monad bind.

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/zkapps_timing.ml
> +      ( Async.Thread_safe.block_on_async_exn (fun () ->
bind

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/zkapps_timing.ml
> +      @@ Async.Thread_safe.block_on_async_exn (fun () ->
bind

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/zkapps_timing.ml
> +      ( Async.Thread_safe.block_on_async_exn (fun () ->
bind

2024-05-02 15:58 UTC, mrmr1993 commented on src/app/test_executive/zkapps_timing.ml
> +      Async.Thread_safe.block_on_async_exn (fun () ->
bind

2024-05-02 15:58 UTC, mrmr1993 commented on src/lib/mina_base/receipt.ml
> +  let empty =
Revert.

2024-05-02 17:02 UTC, mitschabaude commented
!ci-build-me

2024-05-02 17:23 UTC, mrmr1993 commented
!ci-build-me

2024-05-02 17:23 UTC, mrmr1993 commented
!ci-nightly-me

2024-05-02 17:23 UTC, mrmr1993 approved these changes

2024-05-02 18:22 UTC, mrmr1993 commented
!ci-nightly-me

2024-05-02 18:23 UTC, mrmr1993 commented
Nightly run: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1937

2024-05-02 18:23 UTC, mrmr1993 commented
!ci-build-me

2024-05-16 15:38 UTC, mitschabaude commented
!ci-nightly-me

2024-05-16 19:18 UTC, mitschabaude commented
!ci-build-me

2024-05-17 09:28 UTC, mitschabaude commented
!ci-build-me

2024-05-17 10:03 UTC, mitschabaude commented
!ci-nightly-me

2024-05-17 13:50 UTC, mitschabaude commented
!ci-build-me

2024-05-17 14:04 UTC, mitschabaude commented
!ci-build-me

2024-05-17 14:31 UTC, mitschabaude commented
!ci-nightly-me

2024-05-17 15:51 UTC, merged