adding graphql query for snarked ledger
MinaProtocol/mina pull request #15611
Opened 2024-05-07 01:44 UTC by svv232

Explain your changes:
* I added a snarkLedger object to the block object in graphql. The idea is to emulate the snark leger export functionality in the daemon rpc calls in graphql.

Explain how you tested your changes:
* I need some additional assistance testing this. Despite my best efforts, I can't seem to get a block height of greater than size one on my local network. Ideally this query would be run on a network with a reasonably large snark ledger, along with a unit test. If anyone can walk me through doing this, or help me get my local network set up that would be a huge help.

<img width="1233" alt="Screenshot 2024-05-06 at 8 40 31 PM" src="https://github.com/MinaProtocol/mina/assets/23268748/0f383d6e-529e-4166-8de2-c850bb19a3b0">

Ch=
- [ ] Does this close issues? List them
hopefully closes #12706

2024-05-09 19:49 UTC, ghost-not-in-the-shell commented
The PR seems good to me. This can be tested using the mina_local_network script.

2024-05-13 20:59 UTC, mrmr1993 commented
> hopefully closes https://github.com/MinaProtocol/mina/issues/12706

This doesn't quite address the issue, because it only returns the accounts and not the merkle path.

2024-05-13 21:01 UTC, mrmr1993 requested changes

2024-05-13 21:01 UTC, mrmr1993 commented on src/lib/mina_graphql/types.ml
> +                         acc |> Account.to_yojson |> Yojson.Safe.to_basic )
Instead of casting this to JSON, can you try to use the `Types.AccountObj.account` return type?

2024-08-22 23:59 UTC, svv232 commented
this is now supported in #15936

2024-08-22 23:59 UTC, closed without merging