[CI] explicitly select if mainnet should be built
MinaProtocol/mina pull request #15794
Opened 2024-07-04 20:25 UTC by dkijania

After we metg

2024-07-04 20:26 UTC, dkijania commented
!ci-build-me

2024-07-05 15:38 UTC, dkijania commented
!help-merge-me

2024-07-05 15:38 UTC, dkijania commented
Hello, @dkijania 2 new  created to help you port this change to master. Please follow steps to resolve conflict for each mainline branch. PRs will be created automatically after you push merge to porting branches

  
## develop 

```
git fetch && git checkout port/_ci/build_mainnet_and_devnet_in_ci_to_develop && git merge ci/build_mainnet_and_devnet_in_ci
```

Resolve conflict and then 

```
git push
```  
    
  
## compatible 

```
git fetch && git checkout port/_ci/build_mainnet_and_devnet_in_ci_to_compatible && git merge ci/build_mainnet_and_devnet_in_ci
```

Resolve conflict and then 

```
git push
```

2024-07-05 15:45 UTC, dkijania commented
Porting branch #15800 to resolve conflict with develop created. Please merge it in order to solve conflict between head of this PR and develop

2024-07-05 20:55 UTC, dkijania commented
Porting branch #15801 to resolve conflict with compatible created. Please merge it in order to solve conflict between head of this PR and compatible

2024-07-05 21:18 UTC, dkijania commented
!ci-build-me

2024-07-08 18:14 UTC, georgeee requested changes
PR seems to contain a couple of bugs that suggest that testing performed was limited at the point. Overall, PR seems to be implementing what it suggests to implement, however our Dhall code becomes even messier than it was before.

2024-07-08 18:14 UTC, georgeee commented on buildkite/src/Command/MinaArtifact.dhall
> +      let flatten_docker_steps =
```suggestion
      let flattened_docker_steps = 
```

2024-07-08 18:14 UTC, georgeee commented on buildkite/src/Command/MinaArtifact.dhall
> +            flatten_docker_steps)
```suggestion
            flattened_docker_steps)
```

2024-07-08 18:14 UTC, georgeee commented on scripts/rebuild-deb.sh
>      build_daemon_deb
```suggestion
    build_daemon_berkeley_deb
```

2024-07-10 11:41 UTC, mrmr1993 approved these changes

2024-07-10 11:43 UTC, mrmr1993 commented
!approved-for-mainnet

2024-07-10 11:44 UTC, mrmr1993 commented
!ci-build-me

2024-07-10 12:00 UTC, SanabriaRusso commented
I just wanted to run a nightly to make sure: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2216#01909261-e7a4-4c43-a6af-72a6ac8adeff

All build tests passed OK

2024-07-10 12:00 UTC, SanabriaRusso approved these changes

2024-07-10 13:05 UTC, svv232 approved these changes

2024-07-11 16:25 UTC, merged