Martin/persist restore cache
MinaProtocol/mina pull request #15859
Opened 2024-07-23 16:49 UTC by martyall

fixes #15846

2024-07-23 16:51 UTC, martyall commented
!ci-build-me

2024-07-23 16:59 UTC, martyall commented
!ci-build-me

2024-07-23 17:25 UTC, martyall commented
!ci-build-me

2024-07-23 19:10 UTC, martyall commented
!ci-build-me

2024-07-23 21:25 UTC, martyall commented
!ci-build-me

2024-07-23 21:34 UTC, martyall commented
!ci-buid-me

2024-07-23 21:35 UTC, martyall commented
!ci-build-me

2024-07-23 21:39 UTC, martyall commented
!ci-build-me

2024-07-24 14:29 UTC, martyall commented
!ci-build-me

2024-07-24 15:30 UTC, martyall commented
!ci-build-me

2024-07-24 16:24 UTC, martyall commented
!ci-build-me

2024-07-24 16:37 UTC, martyall commented
!ci-build-me

2024-07-24 18:22 UTC, georgeee commented
Instead of forming a tarfile with all the cache entries, I'd suggest to have each cache entry as a standalone `.gz` file (or just as is, without any packaging/compression).

My reasoning is that some of our tests are non-deterministic and they'll use different cache entries. If we overwrite an archive of one run with an archive of another run, we may have some entries always missing, whereas if we don't pack the cache entry, they will add up to a complete coverage eventually

2024-07-24 20:58 UTC, martyall commented
!ci-build-me

2024-07-24 21:03 UTC, martyall commented
!ci-build-me

2024-07-24 21:05 UTC, martyall commented
!ci-build-me

2024-07-24 21:11 UTC, martyall commented
!ci-build-me

2024-07-24 23:59 UTC, martyall commented
!ci-build-me

2024-07-25 01:58 UTC, martyall commented
!ci-build-me

2024-07-25 02:08 UTC, martyall commented
!ci-build-me

2024-07-25 02:40 UTC, martyall commented
!ci-build-me

2024-07-25 02:44 UTC, martyall commented
!ci-build-me

2024-07-25 02:58 UTC, martyall commented
!ci-build-me

2024-07-25 03:03 UTC, martyall commented
!ci-build-me

2024-07-25 09:26 UTC, georgeee requested changes

2024-07-25 09:26 UTC, georgeee commented on buildkite/scripts/lagrange-cache-manager.sh
> +    echo "Cache restored from GCS."
```suggestion
    echo "Lagrange basis cache restored from GCS."
```

2024-07-25 09:26 UTC, georgeee commented on buildkite/scripts/lagrange-cache-manager.sh
> +    echo "No cache found. Starting with a fresh cache."
```suggestion
    echo "No lagrange basis cache found. Starting with a fresh cache."
```

2024-07-25 09:26 UTC, georgeee commented on buildkite/scripts/lagrange-cache-manager.sh
> +  # Find new or changed files by comparing the lists
I suggest just doing `gsutil cp` with an `-n` flag.

This way `gsutil` will copy all files, but skip copying files that already exist on the bucket.

2024-07-25 09:26 UTC, georgeee commented on buildkite/scripts/lagrange-cache-manager.sh
> +  mkdir -p "$cache_dir/pallas" "$cache_dir/vesta"
Suggest moving this line to `restore_cache` function (then `create_cache_dir` can be rmeoved)

2024-07-25 15:45 UTC, martyall commented
@georgeee thanks for taking a look. But right now this is still in draft mode and I'm actually trying to determine whether this is worth doing at all (my theory is that it's not worth adding code to get negligible gain). It would be helpful to hold off looking at this until I request review.

2024-08-01 22:08 UTC, martyall commented
I am going to close this as right now there is only marginal gain for added complexity. I will keep this branch alive in case this comes up in the near future

2024-08-01 22:08 UTC, closed without merging