Remove hard-coded `Precomputed_values.compiled = None`
MinaProtocol/mina pull request #15904
Opened 2024-08-01 22:30 UTC by mrmr1993

2024-08-01 22:30 UTC, mrmr1993 commented
!ci-build-me

2024-08-12 11:53 UTC, georgeee requested changes

2024-08-12 11:53 UTC, georgeee commented on src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
> -        let hashes =
Why keep a command that only prints `[]`/`<empty>`?

Even is we want to keep it, let's simplify the code down to:

```
if json then Core.print "[]\n"
```

2024-08-12 12:40 UTC, mrmr1993 commented
!ci-build-me

2024-08-12 12:48 UTC, georgeee approved these changes

2024-08-12 12:48 UTC, georgeee commented on src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
> +      fun () -> if json then print "[]\n"]
```suggestion
      fun () -> if json then Core.printf "[]\n"]
```
And remove the line above

2024-08-12 17:21 UTC, merged