Patch missing type shapes in a fly
MinaProtocol/mina pull request #16043
Opened 2024-09-12 20:09 UTC by dkijania

When there is a missing reference file we can checkout missing commit , dump type shape and continue compairsion

2024-09-12 20:09 UTC, dkijania commented
!ci-build-me

2024-09-16 07:52 UTC, dkijania commented
!ci-build-me

2024-09-16 10:33 UTC, dkijania commented
!ci-build-me

2024-09-16 17:01 UTC, dkijania commented
!ci-build-me

2024-09-18 08:44 UTC, dkijania commented
!ci-build-me

2024-09-18 09:14 UTC, dkijania commented
!ci-build-me

2024-09-18 11:09 UTC, dkijania commented
!ci-build-me

2024-09-18 16:10 UTC, dkijania commented
!ci-build-me

2024-09-18 16:35 UTC, dkijania commented
!ci-build-me

2024-09-18 21:28 UTC, dkijania commented
!ci-build-me

2024-09-19 07:35 UTC, dkijania commented
!ci-build-me

2024-09-19 08:52 UTC, dkijania commented
!ci-build-me

2024-09-19 11:25 UTC, dkijania commented
!ci-build-me

2024-09-22 18:28 UTC, dkijania commented
!ci-build-me

2024-09-23 12:36 UTC, dkijania commented
!ci-build-me

2024-09-23 21:56 UTC, dkijania commented
!ci-build-me

2024-09-24 11:37 UTC, dkijania commented
!ci-build-me

2024-09-24 16:52 UTC, dkijania commented
!ci-build-me

2024-09-24 19:27 UTC, dkijania commented
!ci-build-me

2024-09-25 07:56 UTC, SanabriaRusso approved these changes

2024-09-26 13:42 UTC, georgeee commented
@dkijania seems like this branch is a bit broken, I see some commits seemingly targeted at `develop`, however the base branch is `compatible`.

2024-09-26 15:12 UTC, mrmr1993 requested changes

2024-09-26 15:12 UTC, mrmr1993 commented on README.md
> +| Develop | Compatible | Master |
This (and other) changes shoudn't be here. Please remove them.

2024-09-29 13:52 UTC, dkijania commented
!ci-build-me

2024-09-30 12:32 UTC, dkijania commented
!ci-build-me

2024-09-30 12:39 UTC, dkijania commented
!ci-build-me

2024-09-30 12:41 UTC, dkijania commented
!ci-build-me

2024-10-01 08:08 UTC, dkijania commented
!ci-build-me

2024-10-02 06:51 UTC, dkijania commented on buildkite/scripts/version-linter-patch-missing-type-shapes.sh
> +    checkout_and_dump $BUILDKITE_COMMIT
Yes, this is only another gate that make sure there is no missing files as this one can be used as  base branch or release branch reference file. I will remove this if

2024-10-02 06:56 UTC, dkijania commented
!ci-build-me

2024-10-02 14:12 UTC, georgeee commented on scripts/version-linter.py
> +  release_branch_commit=find_latest_type_shape_ref_on(release_branch, n=10)
As I mentioned in `develop` twin of this PR, I'm not sure this 10-commit check is a good idea, or necessary.

2024-10-04 07:23 UTC, dkijania commented
!ci-build-me

2024-10-14 08:54 UTC, dkijania commented
!ci-build-me

2024-10-14 13:48 UTC, dkijania commented
!ci-build-me

2024-10-14 17:49 UTC, dkijania commented
!ci-build-me

2024-10-15 08:45 UTC, dkijania commented
!ci-build-me

2024-10-16 18:47 UTC, dkijania commented
!ci-build-me

2024-10-21 12:54 UTC, dkijania commented
!ci-build-me

2024-10-28 10:31 UTC, dkijania commented
!ci-build-me

2024-10-28 13:22 UTC, dkijania commented
!ci-build-me

2024-10-28 15:56 UTC, mrmr1993 approved these changes

2024-10-28 15:56 UTC, mrmr1993 commented
!ci-build-me

2024-10-28 21:51 UTC, merged