[Part 2 of 2] Constants loader and Config loader
MinaProtocol/mina pull request #16187
Opened 2024-10-04 08:59 UTC by martyall

Finish up work started in #16186 . We probably want to merge these 2 at the same time or in close succession 

## The Problem
PR #16186 introduced a standard way for loading constants and config. In order to keep the diff to a minimum, I only ported the code contained in `src/lib` and `mina_cli_entrypoint`. The rest of the codebase still used the old way.

## The solution
This converts the rest of the executables to use the new `Constants` and `Config` loader.

2024-10-04 09:02 UTC, martyall commented
!ci-nightly-me

2024-10-04 16:23 UTC, martyall commented
!ci-nightly-me

2024-10-04 16:24 UTC, martyall commented
nightly results (all important tests passing)
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2666

2024-10-04 16:28 UTC, martyall commented
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2667

2024-10-08 21:37 UTC, georgeee approved these changes

2024-10-08 21:37 UTC, georgeee commented on src/app/test_executive/test_executive.ml
> +  ; config_file : string list
```suggestion
  ; config_files : string list
```

2024-10-09 17:35 UTC, martyall commented
!ci-nightly-me

2024-10-13 05:21 UTC, martyall commented
!ci-build-me

2024-10-17 21:37 UTC, georgeee commented
!ci-build-me

2024-10-20 15:17 UTC, georgeee commented
!ci-build-me

2024-10-20 15:19 UTC, georgeee commented
!ci-build-me

2024-10-22 09:27 UTC, joaosreis approved these changes

2024-10-28 12:12 UTC, mrmr1993 requested changes
Don't change the CLI for all of the tools in a single PR. These are not routine changes, and each previous PR in this chain has been a large headache with breakages.

2024-10-30 13:14 UTC, closed without merging