WIP
MinaProtocol/mina pull request #16254
Opened 2024-10-16 15:16 UTC by dkijania

…sidecar_removal_comp### Welcome 👋

Thank you for contributing to Mina! Please see `CONTRIBUTING.md` if you haven't
yet. In that doc, there are more details around how to start our CI.

If you cannot complete any of the steps below, please ask for help from a core
contributor.

### Incomplete Work

We feel it's important that everyone is comfortable landing incomplete projects
so we don't keep PRs open for too long (especially on develop). To do this we
don't want to forget that something is incomplete, don't want to be blocked on
landing things, and we don't want to land anything that breaks the daemon. We
don't want to forget to test the incomplete things whenever they are completed,
and finally we want to clean up after ourselves: any temporary cruft gets
completely removed before a project is considered done.

To achieve the above, we wish to keep track of incomplete work using a draft of
the release notes. We can share this part of the current draft at anytime with
external contributors. Moreover, we will review this draft during hardforks.

To ship incomplete work, put it behind feature flags -- prefer a runtime
CLI/daemon-config-style flag if possible, and only if necessary fallthrough to
compile time flags. Note that if you put code behind a compile time flag, you
_must_ ensure that CI is building all possible code paths. Don't land something
that doesn't build in CI.

## PLEASE DELETE EVERYTHING ABOVE THIS LINE
---

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2024-10-16 15:25 UTC, dkijania commented
!ci-build-me

2024-10-16 18:37 UTC, dkijania commented
!ci-build-me

2024-10-16 19:10 UTC, dkijania commented
!ci-build-me

2024-10-17 10:58 UTC, dkijania commented
!ci-build-me

2024-10-17 11:06 UTC, dkijania commented
!ci-build-me

2024-10-17 11:33 UTC, dkijania commented
!ci-build-me

2024-10-17 17:52 UTC, dkijania commented
!ci-build-me

2024-10-17 21:24 UTC, dkijania commented
!ci-build-me

2024-10-18 20:24 UTC, dkijania commented
!ci-build-me

2024-10-18 20:54 UTC, dkijania commented
!ci-build-me

2024-10-19 08:38 UTC, dkijania commented
!ci-build-me

2024-10-19 08:57 UTC, dkijania commented
!ci-build-me

2024-10-19 08:59 UTC, dkijania commented
!ci-build-me

2024-10-19 09:25 UTC, dkijania commented
!ci-build-me

2024-10-19 09:27 UTC, dkijania commented
!ci-build-me

2024-10-20 20:22 UTC, dkijania commented
!ci-build-me

2024-10-21 09:19 UTC, georgeee commented on scripts/changelog.sh
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash
```

so that `nix` users could also use it

2024-11-15 20:52 UTC, dkijania commented
!ci-build-me

2024-11-18 09:35 UTC, dkijania commented
!ci-build-me

2025-02-25 19:43 UTC, dkijania commented
!ci-build-me

2025-02-25 20:37 UTC, amc-ie commented
!ci-bypass-changelog

2025-02-25 20:39 UTC, mrmr1993 commented
!ci-bypass-changelog

2025-02-25 21:20 UTC, dkijania commented
!ci-build-me

2025-02-26 08:25 UTC, dkijania commented
!ci-build-me

2025-02-27 07:12 UTC, dkijania commented
!ci-build-me

2025-03-12 14:37 UTC, georgeee requested changes

2025-03-12 14:37 UTC, georgeee commented on scripts/changelog.sh
> +#!/usr/bin/env bash
This script isn't used for CI job, maybe it's better to remove it from PR?

2025-03-12 14:37 UTC, georgeee commented on buildkite/scripts/changelog.sh
> +GITHUB_USERS_ELIGIBLE_FOR_BYPASS="amc-ie mrmr1993"
@dkijania could you also add team leads?

Handles: `deepthiskumar Trivo25 45930 SanabriaRusso nicc georgeee`

2025-03-12 14:37 UTC, georgeee commented on buildkite/src/Jobs/Lint/Changelog.dhall
> +                  "./buildkite/scripts/changelog.sh --trigger ${trigger} --required-change ${reqFile}"
What will `trigger` be set to? Expression above looks quite complex, although I'd expect it to be just `src/` or something along these lines

2025-03-12 14:37 UTC, georgeee commented on buildkite/scripts/changelog.sh
> +COMMIT=$(git log -1 --pretty=format:%H)
Why not simply use `BUILDKITE_COMMIT`?

2025-03-12 14:37 UTC, georgeee commented on buildkite/scripts/changelog.sh
> +if (cat _computed_diff.txt | grep -E -q "$TRIGGER"); then
I think it's better to simplify this logic.

Let's rename `--trigger` to something like `--path` populated into variable `BASE_PATH`.

And then:
```suggestion
if (git diff "${REMOTE}/${BUILDKITE_PULL_REQUEST_BASE_BRANCH}" "$BASE_PATH"); then
```

2025-03-12 14:37 UTC, georgeee commented on buildkite/scripts/changelog.sh
> +    if ! (cat _computed_diff.txt | grep -E -q "$REQUIRED_CHANGE"); then
Let's rename `--required-change` with `--changelog-file` and then simply check if the file exists: 

```suggestion
    if ! [[ -f "$CHANGELOG_FILE" ]]; then
```

2025-03-13 13:44 UTC, dkijania commented
!ci-build-me

2025-03-13 15:02 UTC, georgeee requested changes

2025-03-13 15:53 UTC, dkijania commented on buildkite/scripts/changelog.sh
> +if ! python3 scripts/github/github_info is_pr_commented --comment "$BYPASS_PHRASE" --by $GITHUB_USERS_ELIGIBLE_FOR_BYPASS ; then
Parameter is defined with nargs='+' which should handle multiple entries

2025-03-13 15:54 UTC, dkijania commented
!ci-build-me

2025-03-18 15:27 UTC, georgeee commented on buildkite/scripts/changelog.sh
> +if (git diff --quiet "${REMOTE}/${BUILDKITE_PULL_REQUEST_BASE_BRANCH}" "$BASE_PATH"); then
If the diff is empty, return code will be `0`. I see that clauses in `then` and in `else` need to be swapped for the code to work as intended.

2025-03-18 16:21 UTC, georgeee approved these changes

2025-03-18 16:21 UTC, georgeee commented
!ci-build-me

2025-03-27 17:37 UTC, SanabriaRusso approved these changes

2025-03-27 19:54 UTC, merged