Implement archive test with mocked daemon
MinaProtocol/mina pull request #16329
Opened 2024-11-07 09:21 UTC by dkijania

Introducing quick component test for archive node with mocked daemon which simulates sending precomputed blocks. Test scenario is easy:

- start archive node with runtime config (so genesis block will be included at startup)
- use mina advanced archive-blocks to send precomputed blocks to archive node
- validate all blocks are archived
- run replayer to consistency check

While developing thte test i introduced new mini framework for defining test case with setup i and tear down)

2024-11-07 09:23 UTC, dkijania commented
!ci-build-me

2024-11-07 21:11 UTC, dkijania commented
!ci-build-me

2024-11-08 09:13 UTC, dkijania commented
!ci-build-me

2024-11-08 12:03 UTC, dkijania commented
!ci-build-me

2024-11-10 20:32 UTC, dkijania commented
!ci-build-me

2024-11-17 13:53 UTC, dkijania commented
!ci-build-me

2024-11-17 14:47 UTC, dkijania commented
!ci-build-me

2024-11-18 09:34 UTC, dkijania commented
!ci-build-me

2025-04-23 05:11 UTC, glyh requested changes
For all files that I didn't comment, I think you'll need people more familiar with the tooling to check :)

2025-04-23 05:11 UTC, glyh commented on src/test/mina_automation/fixture/archive.ml
> +
This would also raise if `NETWORK_DATA_FOLDER` is not present, but this is just a minor issue.

2025-06-16 18:30 UTC, dkijania commented on src/test/mina_automation/psql.ml
> +  Util.run_cmd_exn "." psql (creds @ [ "-c"; command; "-t" ]) >>| String.strip
Output of psql adds a lot of whitespaces

2025-06-16 18:33 UTC, dkijania commented on src/test/archive/archive_node_tests/dune
> + (instrumentation (backend bisect_ppx))
hm, if there any missing one then this is a mistake

2025-06-16 21:27 UTC, dkijania commented
!ci-build-me

2025-06-17 11:26 UTC, dkijania commented
!ci-build-me

2025-06-17 13:09 UTC, dkijania commented
!ci-build-me

2025-06-17 20:53 UTC, dkijania commented
!ci-build-me

2025-06-30 19:13 UTC, dkijania commented
!ci-build-me

2025-07-03 18:50 UTC, dkijania commented
!ci-build-me

2025-07-03 21:05 UTC, dkijania commented
!ci-build-me

2025-07-04 11:55 UTC, dkijania commented
!ci-build-me

2025-07-06 18:38 UTC, dkijania commented
!ci-build-me

2025-07-07 06:58 UTC, dkijania commented
!ci-build-me

2025-07-07 13:27 UTC, dkijania commented
!ci-build-me

2025-07-10 07:30 UTC, glyh commented on src/test/mina_automation/psql.ml
> +  Util.run_cmd_exn "." psql (creds @ [ "-c"; command; "-t" ]) >>| String.strip
`-t` strips the column line, how is this dealt with in other places so it'll still work? Or it's not working before?

2025-07-10 10:14 UTC, dkijania commented on src/test/mina_automation/psql.ml
> +  Util.run_cmd_exn "." psql (creds @ [ "-c"; command; "-t" ]) >>| String.strip
In this case we are using output for further processing. Before we just used it for printout, so it wasn't so critical to clean out the output

2025-07-14 02:41 UTC, glyh commented
Background for reviewers:
- [Archive Database Schema](https://raw.githubusercontent.com/MinaProtocol/mina/master/src/app/archive/create_schema.sql)

2025-07-14 02:48 UTC, glyh commented
```
$ ./_build/default/src/app/archive/archive.exe help run
Run an archive process that can store all of the data of Mina

  archive.exe run 

=== flags ===

  [--config-file PATH]          to the configuration file containing the genesis
                                ledger
                                (alias: -config-file)
  [--delete-older-than int]     Delete blocks that are more than n blocks lower
                                than the maximum seen block.
                                (alias: -delete-older-than)
  [--log-json]                  Print log output as JSON (default: plain text)
                                (alias: -log-json)
  [--log-level LEVEL]           Set log level
                                (Internal|Spam|Trace|Debug|Info|Warn|Error|Faulty_peer|Fatal,
                                default: Info)
                                (alias: -log-level)
  [--metrics-port PORT]         metrics server for scraping via Prometheus
                                (default no metrics-server)
                                (alias: -metrics-port)
  [--missing-blocks-width int]  The width of block heights within which missing
                                blocks are reported in Prometheus metrics. If
                                the maximum height in the database is h and
                                missing-blocks-width is n, then
                                Coda_Archive_missing_blocks will report missing
                                blocks between heights max(1, h-n) and h
                                (default 2000)
                                (alias: -missing-blocks-width)
  [--postgres-uri URI]          URI for postgresql database (examples:
                                postgres://admin:codarules@postgres:5432/archiver)
                                (default:
                                postgres://admin:codarules@postgres:5432/archiver)
                                (alias: -postgres-uri)
  [--server-port PORT]          port to launch the archive server (default:
                                3086)
                                (alias: -server-port)
  [-help]                       print this help text and exit
                                (alias: -?)
```

2025-07-14 03:04 UTC, glyh requested changes

2025-07-14 03:04 UTC, glyh commented on buildkite/scripts/build-artifact.sh
> +  src/test/archive/archive_node_tests/archive_node_tests.exe
What is this file for?

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +    Psql.run_command ~connection "Select count(*) from blocks where height > 0"
what does it mean for a block of height 0? They're genesis?

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +    actual_blocks_count |> String.strip |> Int.of_string
I would make it more robust and consider the case the database return some error message that can't be casted to Int.

2025-07-14 03:04 UTC, glyh commented on buildkite/src/Command/ArchiveNodeTest.dhall
> +let Artifacts = ../Constants/Artifacts.dhall
I suggest infra-engs review the dhall parts

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +      Daemon.dispatch_blocks daemon
The name of this function is confusing. I suggest a rename. But I'm fine in follow up PRs

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +      Daemon.dispatch_blocks daemon
Doc from mina cli:
```
Archive a block from a file.

If an archive address is given, this process will communicate with the archive node directly; otherwise it will communicate through the daemon over the rest-server
```

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +      Daemon.dispatch_blocks daemon
So a better name might be `archive_blocks_from_files` instead of `dispatch_blocks`

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +  let connection = Psql.Conn_str archive_uri in
Maybe reuse connection across the whole testing life span?

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +    Psql.run_command ~connection "Select count(*) from blocks where height > 0"
Style: I suggest follow a consistent SQL formatting scheme. 

For example we make all keywords upcased:
```
SELECT COUNT(*) FROM blocks WHERE height > 0
```

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +        "select state_hash from blocks WHERE id=(SELECT max(id) FROM blocks) \
GPT says:
```
SELECT state_hash
FROM blocks
ORDER BY id DESC
LIMIT 1
```

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +    let%bind _ =
I would print the stdout instead of ignoring it for better debuggability

2025-07-14 03:04 UTC, glyh commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +      Replayer.run replayer ~archive_uri
doc for replayer:
```
Replay transactions from Mina archive database

  replayer.exe 

=== flags ===

  --archive-uri URI                  URI for connecting to the archive database
                                     (e.g.,
                                     postgres://$USER@localhost:5432/archiver)
  --input-file file                  File containing the starting ledger
  [--checkpoint-file-prefix string]  Checkpoint file prefix (default:
                                     'replayer')
  [--checkpoint-interval NN]         Write checkpoint file every NN slots
  [--checkpoint-output-folder file]  Folder containing the resulting checkpoints
  [--continue-on-error]              Continue processing after errors
  [--file-log-level LEVEL]           Set log level for the log file
                                     (Internal|Spam|Trace|Debug|Info|Warn|Error|Faulty_peer|Fatal,
                                     default: Trace)
                                     (alias: -file-log-level)
  [--genesis-ledger-dir DIR]         Directory that contains the genesis ledger
  [--log-file FILE]                  Set log file (stores JSON)
                                     (alias: -log-file)
  [--log-json]                       Print log output as JSON (default: plain
                                     text)
                                     (alias: -log-json)
  [--log-level LEVEL]                Set log level
                                     (Internal|Spam|Trace|Debug|Info|Warn|Error|Faulty_peer|Fatal,
                                     default: Info)
                                     (alias: -log-level)
  [--output-file file]               File containing the resulting ledger
  [-build-info]                      print info about this build and exit
  [-version]                         print the version of this build and exit
  [-help]                            print this help text and exit
                                     (alias: -?)
```

2025-07-14 03:04 UTC, glyh commented on src/test/mina_automation/executor.ml
> -            f_local ~args ~prefix:PathFinder.built_name ?env ()
what happened here?

2025-07-14 03:04 UTC, glyh commented on src/test/mina_automation/fixture/archive.ml
> +    (*let%bind.Deferred () = File_system.remove_dir @@ t.temp_dir in*)
I don't like commented code. Please remove it.

2025-07-14 03:04 UTC, glyh commented on src/test/mina_automation/psql.ml
> +        (* Db part of Uri is presented as path therefore it includes leading '/',
This is not crucial

2025-07-14 10:08 UTC, dkijania commented on buildkite/scripts/build-artifact.sh
> +  src/test/archive/archive_node_tests/archive_node_tests.exe
test application. Every test suite has its own. In CI we are just launching it with some args

2025-07-14 10:10 UTC, dkijania commented on src/test/mina_automation/fixture/archive.ml
> +    (*let%bind.Deferred () = File_system.remove_dir @@ t.temp_dir in*)
I commented it just for test. reverting

2025-07-14 10:11 UTC, dkijania commented on src/test/mina_automation/executor.ml
> -            f_local ~args ~prefix:PathFinder.built_name ?env ()
In local mode for executor we don't need to add prefix. That was a bug in implementation that was exposed here

2025-07-14 10:29 UTC, dkijania commented on src/test/archive/archive_node_tests/archive_node_tests.ml
> +    Psql.run_command ~connection "Select count(*) from blocks where height > 0"
> what does it mean for a block of height 0? They're genesis?

Yes, but actually, this might be wrong as genesis block has height = 1. WIll double check

2025-07-14 10:34 UTC, dkijania commented
!ci-build-me

2025-07-14 10:39 UTC, dkijania commented
!ci-build-me

2025-07-14 10:58 UTC, dkijania commented
!ci-build-me

2025-07-14 11:14 UTC, dkijania commented
!ci-build-me

2025-07-14 11:26 UTC, glyh approved these changes

2025-07-14 15:12 UTC, dkijania commented
!ci-build-me

2025-07-14 18:27 UTC, dkijania commented
!ci-build-me

2025-07-14 21:33 UTC, dkijania commented
!ci-build-me

2025-07-15 11:12 UTC, amc-ie approved these changes

2025-07-15 11:20 UTC, merged