Use latest proof-systems/master in Mina
MinaProtocol/mina pull request #16405
Opened 2024-12-09 10:40 UTC by dannywillems

Unifying the branches of proof-systems. `proof-systems/master` wasn't used in Mina, even though all the recent changes are happening there.

Explain your changes:
From commit `b6f5f579c78bd9b4b6ab44b666a9183f74a360fa`
```
git submodule update --init --force --recursive
# First update proof-systems
cd src/lib/crypto/proof-systems
git checkout  8c0ed39e4797dafc6e5e3486dc4fcebec4543623
cd ../
git add proof-systems
git commit -m "Deps/proof-systems: bump up"
# removing the kimchi stubs library for now
# 1. edit .gitsubmodules by removing the kimchi-stubs dir
# 2. edit .git/config to remove kimchi stubs vendor
# 3. Remove git submodules
git rm --cached src/lib/crypto/kimchi_bindings/stubs/kimchi-stubs-vendors
rm -rf src/lib/crypto/kimchi_bindings/stubs/kimchi-stubs-vendors
# 4. Commit changes
# Check that git submodules work
git submodule update --init --force --recursive
```

From now, we will start editing Cargo files and update the files in Mina that have breaking changes:
```

```

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2024-12-09 14:37 UTC, dannywillems commented
!ci-build-me

2024-12-09 15:21 UTC, dannywillems commented
!ci-build-me

2024-12-09 18:59 UTC, dannywillems commented
!ci-build-me

2024-12-10 12:25 UTC, dannywillems commented
!ci-nightly-me

2024-12-10 12:28 UTC, dannywillems commented
!ci-build-me

2024-12-10 16:49 UTC, querolita approved these changes
lgtm

2024-12-10 17:54 UTC, dannywillems commented
> Oh wait, I don't see the removal of the keccak constraints in this PR, is that expected?

Should there be any in Mina?

2024-12-10 21:37 UTC, querolita commented
@dannywillems What I am saying is that it seems like the updated proof-systems submodule is not removing the keccak stuff, in the same way that the proof-systems counterpart PR did. Thus I am wondering if anything went wrong with the merge or if there's still another PR to be done once the proof-systems PR gets merged and the commit is updated.

2024-12-11 13:03 UTC, dannywillems commented
> @dannywillems What I am saying is that it seems like the updated proof-systems submodule is not removing the keccak stuff, in the same way that the proof-systems counterpart PR did. Thus I am wondering if anything went wrong with the merge or if there's still another PR to be done once the proof-systems PR gets merged and the commit is updated.

The proof-systems commit is [c54f985d5fe28dc5f34a275884bee486e0861521](https://github.com/o1-labs/proof-systems/compare/872c8f2d1cae6bc0e46d1cf79655eb4592792b52...c54f985d5fe28dc5f34a275884bee486e0861521), which is the head of [!2868](https://github.com/o1-labs/proof-systems/pull/2868), which includes the changes.

2024-12-11 13:14 UTC, querolita commented
@dannywillems Okay, everything's ok, I was looking at the wrong commit. Reaffirm my accept.

2024-12-11 16:01 UTC, volhovm approved these changes
Great! Overall almost all the changes are renamings and simple refactorings. I didn't see anything that was significantly affecting the protocol logic, which is (I hope) good. 

I'd suggest to run nightlies on this PR before merging. It's quite an important step and it'd be nice to test everything end-to-end!

2025-01-08 19:52 UTC, georgeee requested changes
1. Reviewed the only Ocaml file changed: looks good (almost no change)
3. Ignoring all Rust file changes as I'm not fluent with that codebase
4. What is implication of removing kimchi vendors submodule? I welcome the change, but wonder if it was that easy to remove it, why did we have it in the first place?
5. Commit of `proof-systems` we use is not from `master`, but from another PR https://github.com/o1-labs/proof-systems/pull/2868, requesting changes solely because I'd say it's prudent to merge that PR first

2025-01-12 08:15 UTC, dannywillems commented
!ci-build-me

2025-01-12 08:42 UTC, mrmr1993 commented
It appears that this PR has been rebased. Correspondingly, while we don't have a bot to do so, I am closing it.

2025-01-12 08:42 UTC, closed without merging