Increase test coverage for transaction pool module
MinaProtocol/mina pull request #16415
Opened 2024-12-12 23:01 UTC by dkijania

publish debians only on stable pipelines### Welcome 👋

Thank you for contributing to Mina! Please see `CONTRIBUTING.md` if you haven't
yet. In that doc, there are more details around how to start our CI.

If you cannot complete any of the steps below, please ask for help from a core
contributor.

### Incomplete Work

We feel it's important that everyone is comfortable landing incomplete projects
so we don't keep PRs open for too long (especially on develop). To do this we
don't want to forget that something is incomplete, don't want to be blocked on
landing things, and we don't want to land anything that breaks the daemon. We
don't want to forget to test the incomplete things whenever they are completed,
and finally we want to clean up after ourselves: any temporary cruft gets
completely removed before a project is considered done.

To achieve the above, we wish to keep track of incomplete work using a draft of
the release notes. We can share this part of the current draft at anytime with
external contributors. Moreover, we will review this draft during hardforks.

To ship incomplete work, put it behind feature flags -- prefer a runtime
CLI/daemon-config-style flag if possible, and only if necessary fallthrough to
compile time flags. Note that if you put code behind a compile time flag, you
_must_ ensure that CI is building all possible code paths. Don't land something
that doesn't build in CI.

## PLEASE DELETE EVERYTHING ABOVE THIS LINE
---

Explain your changes:
*

Explain how you tested your changes:
*

Checklist:

- [ ] Dependency versions are unchanged
  - Notify Velocity team if dependencies must change in CI
- [ ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them

* Closes #0000

2024-12-13 11:20 UTC, dkijania commented
!ci-build-me

2025-01-07 10:39 UTC, georgeee commented
I like the idea of extraction of transaction pool tests to a standalone file. Let's restructure the PR in the following way:

1. Create a separate predecessor PR that will move the test code out of `transaction_pool.ml` to `test/` subdirectory
2. Retain in this PR only what's related to **new** tests

@dkijania

2025-01-07 11:37 UTC, georgeee requested changes
_Review is still in progress, posting the first few comments..._

2025-01-07 11:37 UTC, georgeee commented on src/lib/network_pool/test_utils.ml
> +  let ledger_snapshot t =
Suggest to inline it into `src/lib/network_pool/transacation_pool_reorg_tests.ml` and return `Account_spec.t` instead of a tuple

2025-01-07 11:37 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +  let apply_zkapp fee t = create t.key_idx (t.balance - fee) (t.nonce + 1)
Are all zkapps in this test created with with zero account updates?

If so, this looks ok, but let's add a comment in the code about this matter.

2025-01-07 11:37 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +            minor_acc.balance - major_acc.balance < 100_000_000_000
What is the chance that such two accounts won't be found?

Won't the probability of the test being executed be too low?

2025-01-07 20:05 UTC, georgeee requested changes

2025-01-07 20:57 UTC, georgeee requested changes

2025-01-07 20:57 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +  let%bind aux_minor_cmd = Command_spec.gen_single_from minor (sender.key_idx,sender) in
this logic won't imitate the required behavior if `maj1 >= min1`, where `maj1` and `min1` represent the number of txs from `sender` in `major` and `minor` respectively.

I.e. `aux_minor_cmd` will simply be thrown away. We need to add as many aux cmds as necessary to ensure that resulting minor sequence has more transactions from sender than major.

2025-01-07 20:57 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +  (* We need to increase nonce so transaction has a chance to be placed in the pool.
where is the actual increase happening?

2025-01-07 20:57 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +        Array.set spec idx new_account_spec;
What if balance goes negative? Perhaps we set amount to `0` if amount is less than balance. And if balance is less than min fee, throw an exception.

2025-01-07 20:57 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +        Array.set spec idx new_account_spec;
Case of fee applies to zkapp tx above as well

2025-01-07 20:57 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +            let actual_opt = List.find pool_state ~f:(fun (fee_payer_pk, actual_nonce ) ->
Rewrite this and next function: extract calculation of `actual_opt` into a helper function

2025-01-07 20:57 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +              | Some account_spec ->
Extract `sent_blocking_zkapp`, `total_cost` out of match construction (put it before).

Rewrite `match` without ifs:

```
| Some account_spec when sender.nonce < account_spec.nonce -> (..)
| Some account_spec when sent_blocking_zkapp major_specs pk -> (..)
| Some account_spec when account_spec.balance > total_cost  -> (..)
| Some account_spec -> (..)
| None -> (..)
```

2025-01-08 10:51 UTC, dkijania commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +  let apply_zkapp fee t = create t.key_idx (t.balance - fee) (t.nonce + 1)
Maybe name is misleading. apply_zkapp function in context of account_spec is only modify spec state which we are using for tracking balance and nonce. So no zkapp command or update is done. Just noting that from this account zkapp was sent and we are deducting fee and increases nonce

2025-01-08 12:36 UTC, dkijania commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +        let prefix = gen_commands_from_specs (Array.concat [prefix_specs]) test in
I didn't saw it. thanks!

2025-01-08 15:26 UTC, georgeee commented on src/lib/network_pool/transacation_pool_reorg_tests.ml
> +  let find_in_test_keys (x : Keypair.t) =  Array.findi_exn test_keys ~f:(fun _ -> Keypair.equal x)  |> fst
And remove the two lines below

2025-01-13 14:06 UTC, dkijania commented
!ci-build-me

2025-01-13 14:24 UTC, dkijania commented
!ci-build-me

2025-01-14 14:37 UTC, mrmr1993 approved these changes

2025-01-15 02:46 UTC, mrmr1993 requested changes
Partial review; still need to do a full pass. I've also proposed https://github.com/MinaProtocol/mina/pull/16467, which is functionally the same, but with opinionated refactors to help me understand the code better.

2025-01-15 16:10 UTC, dkijania commented
!ci-build-me

2025-01-15 16:11 UTC, dkijania commented
!ci-build-me

2025-01-16 16:34 UTC, dkijania commented
!ci-build-me

2025-01-16 22:39 UTC, georgeee approved these changes
I like the current test implementation, very readable and precise!

I left more than a dozen review comments, but I doubt any of them prevents the test from doing its job alright in the current setting.

I still want these changes to be applied, mostly to make the test more robust (so that it would work practically on any initial ledger), slightly more readable and to test a slightly fuller distribution of cases. But I'm quite fine with applying these changes in a follow-up PR

2025-01-16 22:39 UTC, georgeee commented on src/lib/network_pool/transaction_pool.ml
> +        minor_sequence_length + major_sequence_length + initial_nonce
Why are we adding the nonce of account  to minor sequence length? What if account has nonce of `100000` in the initial ledger?

2025-01-16 22:39 UTC, georgeee commented on src/lib/network_pool/transaction_pool.ml
> +        minor_sequence_length + major_sequence_length + initial_nonce
Is it to ensure that extended minor sequence is longer than number of transactions associated with the account in pre-existing major sequence?

2025-01-16 22:39 UTC, georgeee commented on src/lib/network_pool/transaction_pool.ml
> +                Int.gen_incl 5_000_000_000_000_000 (half_initial_balance / len)
What if `(half_initial_balance / len) < 5_000_000_000_000_000`? will it fail with an exception?

2025-01-16 22:39 UTC, georgeee commented on src/lib/network_pool/transaction_pool.ml
> +                Int.gen_incl 5_000_000_000_000_000 (half_initial_balance / len)
So, I just checked that initial balance is always 900mln. I still see little benefit in hardcoding the `5mln` amount here

2025-01-16 22:39 UTC, georgeee commented on src/lib/network_pool/transaction_pool.ml
> +        ; minor_commands = Array.append minor_commands aux_minor_cmd
Is it possible to mix aux commands (which are expected to be dropped) with the regular commands from `minor_commands`? Or just generate some new random commands and run `gen_merge` on this new sequence and `aux_commands`. We want to ensure that no valid tx from other account is dropped together with aux commands that need to be dropped.

2025-01-20 20:08 UTC, dkijania commented on src/lib/network_pool/transaction_pool.ml
> +        minor_sequence_length + major_sequence_length + initial_nonce
Exactly, we need to take into consideration case in which major branch has more transactions for particular account. Therefore on minor we need to generate more transaction to keep up with nonce

2025-01-20 20:10 UTC, dkijania commented on src/lib/network_pool/transaction_pool.ml
> +                Int.gen_incl 5_000_000_000_000_000 (half_initial_balance / len)
hm, so what should be the minimal amount ? should it be related to half_initial_balance?

2025-01-20 21:34 UTC, dkijania commented
!ci-build-me

2025-01-20 21:43 UTC, dkijania commented on src/lib/network_pool/transaction_pool.ml
> +                  if sender.nonce < Simple_account.nonce account_spec then (
after changing find_by_key_idx i had to modify match back to if-else

2025-01-20 21:44 UTC, dkijania commented on src/lib/network_pool/transaction_pool.ml
> +      let recieved_amount =
Another safe guard to make sure we deduct correct amount from account balance

2025-01-21 10:20 UTC, georgeee commented on src/lib/network_pool/transaction_pool.ml
> +                Int.gen_incl 5_000_000_000_000_000 (half_initial_balance / len)
yeah, let's make it proportional to `half_initial_balance/len`

2025-01-21 12:02 UTC, dkijania commented
!ci-build-me

2025-01-21 12:52 UTC, mrmr1993 approved these changes

2025-01-21 13:17 UTC, merged