Use runtime config accounts for replayer input and output
MinaProtocol/mina pull request #6263
Opened 2020-10-06 02:22 UTC by deepthiskumar

Added the remaining account fields to `Runtime_config.Accounts.Single.t` (as optional) 
to have a single account format for both daemon and the transaction replayer

Note: The Dhall types for the new fields are all texts which probably isn't correct

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

Closes #0000
Closes #0000

2020-10-06 11:25 UTC, mrmr1993 requested changes
I am deeply unhappy about making `Runtime_config` depend on `Coda_base`. Please create json-friendly representations for the relevant types in `Runtime_config` and do the conversion in `Genesis_ledger_helper`.

2020-10-06 17:24 UTC, deepthiskumar commented
> I am deeply unhappy about making `Runtime_config` depend on `Coda_base`. Please create json-friendly representations for the relevant types in `Runtime_config` and do the conversion in `Genesis_ledger_helper`.

Is it because of a dependency cycle that may occur in the future?

2020-10-07 14:27 UTC, bkase commented on src/lib/coda_base/account_timing.ml
> +let dhall_type = Ppx_dhall_type.Dhall_type.Text
ah I think you want to derive this instead, @psteckler can give more context

2020-10-07 23:08 UTC, deepthiskumar commented
Separated the representation of account fields in `Runtime_config` from the types in `account.ml`
@psteckler @mrmr1993 Any suggestion for representing snapp accounts in the config?

2020-10-08 22:11 UTC, psteckler commented
would it be useful to have a test that the coercions between runtime accounts and `Coda_base` accounts are inverses?

2020-10-09 12:09 UTC, mrmr1993 requested changes

2020-10-09 12:09 UTC, mrmr1993 commented on src/lib/runtime_config/runtime_config.ml
> +        (*TODO: representation for the snapp account type*)
This TODO and the one below should be done. The type is effectively

```ocaml
{state: Field.t list; verification_key: string}
```

The state list has fixed length 8 (anything else should be an error) and the verification key can just be the binary encoding of a `Pickles.Side_loaded_verification_key.t`, which should be handled in `Genesis_ledger_helper`.

Once this is done, can you move `Snapp_lib`'s contents back into `Coda_base`? I agree that it should be broken up, but the natural divisions to my mind are `Coda_account`, `Coda_ledger` and `Coda_transactions`, and nothing else seems to benefit from its being isolated.

2020-10-10 01:16 UTC, mrmr1993 commented on src/lib/runtime_config/runtime_config.ml
> +          { stake: bool
Yes, in the interest of the config file being as permissive as possible, we should allow them to specify a subset of the fields and fill the rest with defaults.

2020-10-13 02:17 UTC, mrmr1993 approved these changes
Excellent, good to go on my side!

2020-10-13 03:08 UTC, merged