4.1-pre-release
MinaProtocol/mina pull request #6622
Opened 2020-11-07 02:32 UTC by lk86

Tighten up flags to daemon in default charts, rename package to mina, prepare for tagging / branch cut. Also updates coda-automation to match master w/ the latest docker image, genesis ledger, etc. to use for the community qa net.

2020-11-09 19:33 UTC, psteckler commented
As I mentioned to @lk86, I have a branch that uses the latest `bisect_ppx`, and eliminates the need to mention `--conditional`. The ppx will be mentioned in an `instrumentation` clause instead of in the `pps` clause.

It's a big change, and it's low priority, so it may take some time before I make it into a PR.

2020-11-10 22:55 UTC, mrmr1993 approved these changes
The script in `scripts/archive/build-release-archives.sh` probably wants updating too. Other than that and my other comment, LGTM.

2020-11-10 22:55 UTC, mrmr1993 commented on dockerfiles/Dockerfile-rosetta
> +RUN sed -i 's/+bmi2,+adx/-bmi2,-adx/g' src/lib/zexe/snarky-bn382/dune
This probably wants to patch `src/lib/marlin_plonk_bindings/stubs/dune` as well.

2020-11-11 00:36 UTC, nholland94 approved these changes

2020-11-11 01:44 UTC, mrmr1993 requested changes

2020-11-11 01:44 UTC, mrmr1993 commented on scripts/publish-deb.sh
> +'--no-lock '\
NOOOOOOO! Delete the lockfile as described in the comment above, don't remove the lock flag!!

2020-11-11 01:46 UTC, mrmr1993 approved these changes

2020-11-11 03:53 UTC, merged