Updated Rosetta API to encode random oracle input as hex string
MinaProtocol/mina pull request #6703
Opened 2020-11-13 18:25 UTC by jspada

* Made render() serialize random oracle input to hex
    * Made of_render() deserialize random oracle input from hex
    * Fixed comment describing format of random oracle input
    * Fixed some invalid JSON in curl Rosetta construction tests
    * Added required public_keys field to metadata and payloads requests
    * Created new construction/parse and construction/payloads tests

Thank you for contributing to Coda! Please see `CONTRIBUTING.md` if you haven't
yet. In that doc, there are more details around how to start our CI.

Explain your changes here.

Explain how you tested your changes here.

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

Closes #0000
Closes #0000

2020-11-13 18:56 UTC, bkase requested changes

2020-11-13 18:56 UTC, bkase commented on scripts/git_hooks/pre-commit
> +# fi
can you revert this change? (by the way, you can `git commit -n` to skip this step)

2020-11-13 20:01 UTC, bkase approved these changes

2020-11-18 03:13 UTC, mrmr1993 commented
!ci-build-me

2020-11-19 02:46 UTC, mrmr1993 commented
!ci-build-me

2020-11-19 13:55 UTC, mrmr1993 commented
!ci-build-me

2020-11-19 14:40 UTC, merged