int yojson coding for nonces
MinaProtocol/mina pull request #7257
Opened 2020-12-23 22:34 UTC by psteckler

Use `int` Yojson coding for nonces, instead of `string`, which is slower.

2020-12-23 22:47 UTC, mrmr1993 requested changes
You'll need to ensure that nonces in  `Coda_transition.External_transition.Precomputed_block.to_yojson` are still string-encoded before we can merge this.

2020-12-23 23:16 UTC, psteckler commented
> You'll need to ensure that nonces in `Coda_transition.External_transition.Precomputed_block.to_yojson` are still string-encoded before we can merge this.

@mrmr1993 I believe they'll change. Is the worry that existing precomputed blocks won't decode?

2020-12-23 23:52 UTC, mrmr1993 commented
> Is the worry that existing precomputed blocks won't decode?

We've committed to the encoding that they're currently in for an external partner. The encoding must not change.

2020-12-23 23:55 UTC, psteckler commented
> We've committed to the encoding that they're currently in for an external partner. The encoding must not change.

In that case, I'll keep the encoding, and change the comment.

2020-12-24 00:10 UTC, mrmr1993 commented
> In that case, I'll keep the encoding, and change the comment.

It's fine to change it everywhere else, we just need to make sure that the deriver used for those values is stable.

2020-12-24 00:14 UTC, psteckler commented
> It's fine to change it everywhere else, we just need to make sure that the deriver used for those values is stable.

I think it'd be difficult to special-case the nonce yojson just for this case, it's buried deep in one of the types.

2020-12-24 00:21 UTC, mrmr1993 approved these changes

2020-12-24 01:07 UTC, merged