Remove offline timeout shutdown
MinaProtocol/mina pull request #7974
Opened 2021-02-18 23:22 UTC by psteckler

Remove the code that starts a shutdown timer when a node is `Offline`.

Tested that the sync status still updates with `client status` on a local network.

Closes #7970.

2021-02-18 23:27 UTC, nholland94 requested changes
We discussed adding an error log in place of the shutdown. Can we still do that? We can keep that error silent if `is_seed` is true.

2021-02-18 23:28 UTC, psteckler commented
> We discussed adding an error log in place of the shutdown.

Yes, can put that in.

2021-02-18 23:29 UTC, deepthiskumar requested changes
Instead of crashing we want to add an error log saying the node was offline for 15 mins and suggest checking if they have forwarded the port correctly

2021-02-18 23:45 UTC, nholland94 commented on src/lib/mina_lib/mina_lib.ml
> +          offline_timeout := None
If the timeout had already triggered by this point, would be nice to give an info log saying that the node is now back online.

2021-02-19 00:10 UTC, psteckler commented
@nholland94 @deepthiskumar Made requested changes, I believe.

2021-02-19 00:17 UTC, jrwashburn commented
I really prefer this something that can be enabled/disabled from coda client CLI. Other than the unique edge case bootstrapping a new network, when is this actually valuable? I prefer termination to hanging out offline relatively quietly. Why is it good to stay up, offline?

2021-02-19 00:47 UTC, nholland94 commented
> I really prefer this something that can be enabled/disabled from coda client CLI. Other than the unique edge case bootstrapping a new network, when is this actually valuable? I prefer termination to hanging out offline relatively quietly. Why is it good to stay up, offline?

Having nodes crash after 15 minutes of inactivity on the network has the effect that the entire network can crash if no one is producing blocks or sending transactions for 5 slots. That's a bad thing, and we never want that to happen, but this behavior means that the network will just shut down if that happens, which only makes things worse. Note that your node will still crash if it cannot connect to peers. It's only that now it will not crash if the network has been silent for a few slots.

2021-02-19 00:47 UTC, nholland94 approved these changes

2021-02-19 01:13 UTC, deepthiskumar approved these changes

2021-02-19 18:21 UTC, aneesharaines commented
!approved-for-mainnet

2021-02-19 18:24 UTC, merged