Add Watchdog Postgres max observed block metric collector
MinaProtocol/mina pull request #8116
Opened 2021-03-04 20:27 UTC by 0x0I

Also add testnet alert for tracking rate of increase exceeds designated threshold for each testnet postgres instance.

**Test:** Buildkite CI

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

Closes #8063

2021-03-09 23:28 UTC, deepthiskumar requested changes

2021-03-09 23:28 UTC, deepthiskumar commented on automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
> +      description: "The rate of {{ $value }} new blocks observed by archive postgres instances is low on network {{ $labels.testnet }}."
Could you change this to a warning? It is not critical if the block height doesn't increase by one. I think high unparented block count and missing block count being > 30 would be sufficient for critical alerts.

2021-03-10 16:11 UTC, 0x0I commented on automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
> +    expr: max by (testnet) (max_over_time(Coda_Archive_unparented_blocks ${rule_filter} [${alerting_timeframe}])) > 1
>=

2021-03-10 20:42 UTC, deepthiskumar approved these changes

2021-03-10 23:06 UTC, merged