limit local snark work broadcast
MinaProtocol/mina pull request #9011
Opened 2021-06-09 08:26 UTC by deepthiskumar

limit local snark work broadcasts to avoid being rejected by peers based on the current rate limit values.

2021-06-09 14:35 UTC, mrmr1993 approved these changes

2021-06-09 14:35 UTC, mrmr1993 commented on src/lib/mina_lib/mina_lib.ml
> +              log_rate_limiter_occasionally rl ~label:"local_transactions" ;
Nit: this also applies to rebroadcast of non-local transactions; perhaps the message should be `transactions`?

2021-06-09 15:58 UTC, mrmr1993 requested changes
I'd misunderstood you when we were talking OOB about the `inclusion_table`. I think we still need it -- or something like it -- to prevent us from rebroadcasting snark work until its statement falls off the edge of the frontier.

I originally thought you were talking about keeping work around during a re-org, but I guess that's a far more complicated problem. Probably we should just leave the `inclusion_table` as is.

2021-06-09 16:01 UTC, deepthiskumar commented
> I'd misunderstood you when we were talking OOB about the `inclusion_table`. I think we still need it -- or something like it -- to prevent us from rebroadcasting snark work until its statement falls off the edge of the frontier.
> 
> I originally thought you were talking about keeping work around during a re-org, but I guess that's a far more complicated problem. Probably we should just leave the `inclusion_table` as is.

We only rebroadcast work from the last 10 blocks in the best chain. 
https://github.com/MinaProtocol/mina/blob/bfa47f1dedcaef551ed7a78d359bcf78c0bc5edb/src/lib/network_pool/snark_pool.ml#L535

2021-06-10 19:55 UTC, nholland94 approved these changes

2021-06-11 00:14 UTC, deepthiskumar commented
Discussed with @mrmr1993 some more- with the inclusion table we were essentially only rebroadcasting work from the latest scan state (if they were no re-orgs). But we do want to rebroadcast work from scan state of older blocks given there are many tiny forks. But 10 blocks seems unnecessary and will go over the current  rate limit. So now, rebroadcasting work from the scan state of last 3 blocks in the best chain. This should help with the rate limiting problem cc @nholland94

2021-06-11 03:35 UTC, mrmr1993 approved these changes
After talking OOB, I'm convinced that it's better to rebroadcast older snark work from the last 3 blocks, and I'm happy approving this in its current version. This should be an improvement in all aspects of our snark pool behaviour.

There are still issues around rate limiting, but fixing those fully could end up a significant undertaking, and bitswap will fix these issues properly anyway.

2021-06-16 01:26 UTC, merged