archive snapp txs
MinaProtocol/mina pull request #9731
Opened 2021-10-29 16:27 UTC by A-Manning

2021-11-02 22:10 UTC, deepthiskumar commented on src/app/archive/archive_lib/processor.ml
> +    let%bind (element_ids : (int, 'n) Vector.vec) =
based on https://www.postgresql.org/docs/9.1/arrays.html it seems like we can use `Caqti_type.string` to represent array values when inserting. In this case it'd be `element_ids= '{2,3,4,..}'` and when retrieving, we could parse the same string to an ocaml array

2021-11-02 22:10 UTC, deepthiskumar commented on src/app/archive/archive_lib/processor.ml
> +           "SELECT id FROM snapp_state_data_array WHERE element_id = ?")
suggestion: rename `element_id` to `element_ids`?

2021-11-02 22:23 UTC, psteckler commented on src/app/archive/snapp_tables.sql
> +( list_hash                text             NOT NULL
as discussed via PM, this table can be removed: the `events_list_hash` and `rollup_events_list_hash` can be replaced by an array of ints, representing a list of arrays, where each int is the id of a `snapp_state_data_array`

that eliminates a level of indirection, and is easier to understand, I'd offer

2021-11-02 22:26 UTC, psteckler commented on src/app/archive/create_schema.sql
> +( list_hash                text             NOT NULL
I think we can eliminate this indirection, too.

In `snapp_commands`, we can make `snapp_other_parties` an array of ints, where each int is the id of a `snapp_party` entry.

2021-11-02 22:35 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +  let find_opt (module Conn : CONNECTION) (fp : Pickles.Backend.Tick.Field.t) =
Could factor out common code of `find/find_opt`, pass in `Conn.find/find_opt` as needed

2021-11-02 22:41 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +           "SELECT id FROM snapp_permissions\n\
maybe use OCaml multiline string, to avoid backslashes:
```
{sql|
   ...
|sql}
```

2021-11-02 22:43 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +          (Caqti_request.find_opt Caqti_type.int typ
this expression is common to `find`, maybe factor it out

2021-11-02 22:57 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +        (Caqti_request.find_opt typ Caqti_type.int
ditto ... use multiline strings

2021-11-02 22:58 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +           \           WHERE snarked_ledger_hash_id = ?\n\
multiline string

2021-11-02 22:59 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,)
is there an extra comma here?

2021-11-08 18:28 UTC, psteckler commented on src/app/archive/snapp_tables.sql
> +, edit_sequence_state        snapp_auth_required_type    NOT NULL
nit: fix indentation

2021-11-08 19:29 UTC, psteckler requested changes
a few nits

2021-11-08 19:29 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +        With_hash.Stable.V1.t) =
`With_hash.Stable.Latest.t`, should not mention specific version numbers

2021-11-08 19:29 UTC, psteckler commented on src/app/archive/archive_lib/processor.ml
> +let select_cols ~(select : string) ~(table_name : string)
would it be better to use an option type for `tannot`, instead of relying on the empty string to indicate there's no annotation?

2021-11-08 20:32 UTC, lk86 approved these changes

2021-11-09 23:05 UTC, imeckler approved these changes

2021-11-10 18:22 UTC, psteckler approved these changes

2021-11-10 18:22 UTC, merged