WIP: Party protocol state predicate
MinaProtocol/mina pull request #9855
Opened 2021-11-19 16:59 UTC by A-Manning

2021-12-08 18:20 UTC, mrmr1993 requested changes
A few small changes, but generally lgtm

2021-12-08 18:20 UTC, mrmr1993 commented on src/lib/mina_base/parties_logic.ml
> +    let parties_protocol_state_predicate_satisfied =
Can we change this to always check, and move the `start_data.protocol_state_predicate` into the fee-payer party?

2021-12-08 18:20 UTC, mrmr1993 commented on src/lib/transaction_snark/transaction_snark.ml
> +             ; protocol_state = _ (* FIXME: is this needed? *)
`This is checked by parties_logic`.

2021-12-08 18:20 UTC, mrmr1993 commented on src/lib/mina_base/transaction_logic.ml
> +           ; protocol_state = _ (* FIXME: should this be checked here? *)
`This is checked by parties_logic`.

2021-12-08 18:20 UTC, mrmr1993 commented on src/lib/mina_base/snapp_generators.ml
> +  let%map protocol_state = Snapp_predicate.Protocol_state.gen in
This will (usually) fail, since the predicate will be random. Should we use the logic we have for the main predicate instead?

2021-12-17 14:04 UTC, deepthiskumar reviewed
Could you please update the archive schema with the new field?

2021-12-17 17:51 UTC, A-Manning commented
> Could you please update the archive schema with the new field?

Done

2021-12-17 18:22 UTC, mrmr1993 approved these changes
Fab!

2021-12-20 14:59 UTC, merged